/* eslint-disable max-len */

export const CUTE_BIOS = [
  "🌸 Sweet chaos in a human body | 📚 Bookworm | 🍰 Dessert addict | Spreading smiles ✨",
  "🌷 Made of sunshine, stardust & magic ✨ | 💕 Love wins",
  "🧸 Sunshine girl | cat lover | 💕 be happy 💕",
  "🍰 Sunshine girl | cloud watcher | dreaming big ☁️ 🌸",
  "🌸 Sunshine girl | nature seeker | 🧸 living gently 🕊️",
  "🐰 Born to bloom | star gazer | living gently 🕊️ ✨",
  "✨ Smiling since day one | star gazer | be kind 🌻 💕",
  "Kindness is key • coffee addict • dreaming big ☁️ 🍰",
  "Kindness is key • dream catcher • always sweet 🌸 🐰",
  "🌻 Sunshine girl | cloud watcher | 🧸 be happy 💕",
  "✨ Sunshine girl | cat lover | living gently 🕊️ 🎀",
  "🐰 Sunshine girl | star gazer | be happy 💕 🌻",
  "✨ Kindness is key | music listener | 🎀 living gently 🕊️",
  "Smiling since day one • cloud watcher • living gently 🕊️ 💕",
  "🌻 Spreading magic | cloud watcher | living gently 🕊️ 🌸",
  "✨ Sweet soul | music listener | spread joy 🎀 🎀",
  "🐰 Quiet dreamer | music listener | 🍰 living gently 🕊️",
  "💕 Soft and sweet | book collector | 🧸 be happy 💕",
  "🍰 Born to bloom | cloud watcher | be happy 💕 🌻",
  "🎀 Smiling since day one | cloud watcher | glow daily 💫 🌸",
  "Smiling since day one • book collector • spread joy 🎀 🎀",
  "🌸 Quiet dreamer | dessert lover | 🎀 be happy 💕",
  "Born to bloom • dream catcher • be kind 🌻 🎀",
  "✨ Smiling since day one | dessert lover | 💕 always sweet 🌸",
  "💕 Sunshine girl | dream catcher | living gently 🕊️ 🌻",
  "🌻 Born to bloom | cloud watcher | always sweet 🌸 🐰",
  "🧸 Sunshine girl | music listener | be happy 💕 🌸",
  "🐰 Quiet dreamer | coffee addict | 🎀 dreaming big ☁️",
  "💕 Smiling since day one | book collector | ✨ glow daily 💫",
  "Quiet dreamer • star gazer • living gently 🕊️ 🧸",
  "🎀 Kindness is key | dessert lover | glow daily 💫 🧸",
  "🧸 Sunshine girl | music listener | always sweet 🌸 🌸",
  "🌸 Sweet soul | nature seeker | dreaming big ☁️ 🌻",
  "🐰 Born to bloom | nature seeker | 🧸 be happy 💕",
  "🐰 Smiling since day one | dessert lover | living gently 🕊️ 🍰",
  "Sunshine girl • coffee addict • spread joy 🎀 🌻",
  "🌸 Soft and sweet | cat lover | 🍰 dreaming big ☁️",
  "🧸 Kindness is key | coffee addict | living gently 🕊️ 🐰",
  "🐰 Heart of gold | book collector | be happy 💕 🧸",
  "🌸 Soft and sweet | cloud watcher | dreaming big ☁️ 🎀",
  "Smiling since day one • star gazer • glow daily 💫 🐰",
  "Sweet soul • book collector • spread joy 🎀 🌸",
  "🐰 Soft and sweet | dream catcher | spread joy 🎀 💕",
  "🌸 Spreading magic | nature seeker | always sweet 🌸 🌻",
  "🌸 Sweet soul | dessert lover | making magic ✨ 🎀",
  "🍰 Sunshine girl | coffee addict | 🎀 living gently 🕊️",
  "Flower child • cat lover • dreaming big ☁️ 🍰",
  "✨ Flower child | music listener | living gently 🕊️ 🍰",
  "Spreading magic • dessert lover • be kind 🌻 🎀",
  "🧸 Quiet dreamer | coffee addict | dreaming big ☁️ ✨",
  "🌻 Kindness is key | coffee addict | living gently 🕊️ ✨",
  "🌸 Soft and sweet | cloud watcher | ✨ be happy 💕",
  "Sunshine girl • book collector • be happy 💕 🎀",
  "🧸 Spreading magic | nature seeker | ✨ be kind 🌻",
  "Soft and sweet • dream catcher • always sweet 🌸 🎀",
  "💕 Sweet soul | cat lover | be kind 🌻 ✨",
  "🌸 Soft and sweet | cloud watcher | spread joy 🎀 🎀",
  "Smiling since day one • cloud watcher • always sweet 🌸 🌻",
  "Smiling since day one • cat lover • be happy 💕 🌻",
  "🌻 Flower child | nature seeker | 🍰 dreaming big ☁️",
  "💕 Smiling since day one | nature seeker | making magic ✨ 🍰",
  "🧸 Smiling since day one | music listener | spread joy 🎀 ✨",
  "🐰 Sunshine girl | star gazer | always sweet 🌸 🧸",
  "🧸 Soft and sweet | music listener | 🌸 be happy 💕",
  "Flower child • star gazer • be kind 🌻 ✨",
  "🌻 Kindness is key | cloud watcher | spread joy 🎀 🌸",
  "🌸 Spreading magic | book collector | 🎀 be happy 💕",
  "Heart of gold • music listener • be kind 🌻 🍰",
  "🌸 Quiet dreamer | nature seeker | be happy 💕 🍰",
  "🌻 Born to bloom | cloud watcher | living gently 🕊️ 🍰",
  "Kindness is key • music listener • dreaming big ☁️ ✨",
  "🧸 Heart of gold | dream catcher | 🍰 making magic ✨",
  "Heart of gold • book collector • be happy 💕 🍰",
  "Spreading magic • nature seeker • spread joy 🎀 🌻",
  "Soft and sweet • nature seeker • glow daily 💫 💕",
  "🧸 Born to bloom | music listener | dreaming big ☁️ ✨",
  "Flower child • book collector • always sweet 🌸 🌸",
  "🍰 Quiet dreamer | coffee addict | 🧸 glow daily 💫",
  "🧸 Heart of gold | dessert lover | 💕 spread joy 🎀",
  "🧸 Sweet soul | coffee addict | 💕 spread joy 🎀",
  "Born to bloom • dessert lover • always sweet 🌸 🧸",
  "🐰 Smiling since day one | dessert lover | 🍰 be kind 🌻",
  "🐰 Soft and sweet | book collector | glow daily 💫 ✨",
  "Spreading magic • cloud watcher • glow daily 💫 🧸",
  "Sunshine girl • dream catcher • living gently 🕊️ ✨",
  "Born to bloom • coffee addict • making magic ✨ 💕",
  "🍰 Smiling since day one | nature seeker | 🌻 dreaming big ☁️",
  "Soft and sweet • star gazer • always sweet 🌸 🧸",
  "Quiet dreamer • cat lover • spread joy 🎀 🐰",
  "🧸 Spreading magic | star gazer | spread joy 🎀 🐰",
  "Spreading magic • star gazer • glow daily 💫 🌸",
  "Heart of gold • book collector • glow daily 💫 💕",
  "Quiet dreamer • cat lover • dreaming big ☁️ 🍰",
  "🍰 Smiling since day one | cat lover | be happy 💕 🌻",
  "Soft and sweet • music listener • be kind 🌻 🍰",
  "🌸 Spreading magic | coffee addict | glow daily 💫 🌻",
  "🧸 Sunshine girl | cat lover | 🌸 always sweet 🌸",
  "🐰 Smiling since day one | nature seeker | 🎀 making magic ✨",
  "🌻 Flower child | dessert lover | 💕 be happy 💕",
  "✨ Quiet dreamer | coffee addict | 🎀 making magic ✨",
];

export const STYLISH_BIOS = [
  "👑 Not everyone can handle me | 💎 Diamonds are my best friends | 🖤 Luxury is a mindset",
  "✨ Elegance is the only beauty | 💅 Fashion first",
  "🥂 Dressed in confidence | fashion collector | always polished 💍 💄",
  "🖤 Golden energy | chic curator | 👑 living deluxe 🥂",
  "👠 Dressed in confidence | red lip wearer | 👑 always polished 💍",
  "Living in style • perfume lover • always polished 💍 ✨",
  "🥂 Living in style | velvet dreamer | 💅 pure luxury 💎",
  "✨ Class and sass | fashion collector | 🥂 high goals 👠",
  "Golden energy • fashion collector • style speaks 💄 💄",
  "🥂 Luxury mindset | chic curator | high goals 👠 👠",
  "Luxury mindset • red lip wearer • pure luxury 💎 ✨",
  "🖤 Aesthetic obsession | red lip wearer | 💎 never basic 💅",
  "🥂 Fashion enthusiast | makeup addict | ✨ effortlessly chic ✨",
  "✨ Fashion enthusiast | velvet dreamer | high goals 👠 💎",
  "💄 Aesthetic obsession | chic curator | 🖤 always polished 💍",
  "👠 Golden energy | red lip wearer | 🥂 high goals 👠",
  "Class and sass • red lip wearer • style speaks 💄 ✨",
  "💄 Aesthetic obsession | chic curator | living deluxe 🥂 👠",
  "Class and sass • heels devotee • effortlessly chic ✨ 💄",
  "💄 Golden energy | fashion collector | living deluxe 🥂 🖤",
  "Living in style • heels devotee • never basic 💅 💎",
  "💅 Dressed in confidence | perfume lover | never basic 💅 ✨",
  "✨ Dressed in confidence | fashion collector | high goals 👠 👠",
  "Dressed in confidence • fashion collector • high goals 👠 👑",
  "💅 Styled with grace | perfume lover | pure luxury 💎 🖤",
  "Fashion enthusiast • makeup addict • always polished 💍 💄",
  "🖤 Luxury mindset | fashion collector | 💎 always polished 💍",
  "🖤 Styled with grace | chic curator | effortlessly chic ✨ 👑",
  "Fashion enthusiast • heels devotee • living deluxe 🥂 💅",
  "Luxury mindset • velvet dreamer • never basic 💅 💎",
  "💄 Aesthetic obsession | velvet dreamer | 🖤 living deluxe 🥂",
  "👑 Golden energy | chic curator | 💄 always polished 💍",
  "👑 Main character vibes | fashion collector | pure luxury 💎 💎",
  "👑 Aesthetic obsession | fashion collector | ✨ high goals 👠",
  "✨ Aesthetic obsession | black outfit lover | 👑 never basic 💅",
  "🖤 Dressed in confidence | black outfit lover | style speaks 💄 💎",
  "Fashion enthusiast • perfume lover • never basic 💅 💎",
  "💅 Class and sass | velvet dreamer | 🥂 never basic 💅",
  "Luxury mindset • makeup addict • high goals 👠 👠",
  "👠 Living in style | makeup addict | 🥂 pure luxury 💎",
  "💎 Luxury mindset | fashion collector | always polished 💍 ✨",
  "👑 Living in style | fashion collector | 🥂 style speaks 💄",
  "💎 Dressed in confidence | velvet dreamer | 💄 always polished 💍",
  "Living in style • velvet dreamer • high goals 👠 💎",
  "✨ Class and sass | heels devotee | never basic 💅 👑",
  "🖤 Golden energy | chic curator | 💎 pure luxury 💎",
  "👑 Chic and classy | makeup addict | effortlessly chic ✨ ✨",
  "Main character vibes • velvet dreamer • never basic 💅 🖤",
  "💅 Luxury mindset | chic curator | high goals 👠 🥂",
  "Golden energy • heels devotee • living deluxe 🥂 🖤",
  "🖤 Class and sass | fashion collector | staying iconic 👑 ✨",
  "Luxury mindset • velvet dreamer • style speaks 💄 👠",
  "Living in style • chic curator • effortlessly chic ✨ 🥂",
  "Dressed in confidence • red lip wearer • high goals 👠 🥂",
  "👑 Dressed in confidence | heels devotee | style speaks 💄 ✨",
  "💅 Class and sass | velvet dreamer | 🥂 staying iconic 👑",
  "🖤 Main character vibes | makeup addict | 👠 high goals 👠",
  "🥂 Chic and classy | makeup addict | 👠 style speaks 💄",
  "💄 Luxury mindset | perfume lover | living deluxe 🥂 🖤",
  "👑 Styled with grace | black outfit lover | living deluxe 🥂 ✨",
  "Aesthetic obsession • perfume lover • staying iconic 👑 👠",
  "💅 Living in style | red lip wearer | 💄 always polished 💍",
  "💅 Chic and classy | heels devotee | 👑 pure luxury 💎",
  "Chic and classy • chic curator • high goals 👠 💅",
  "Aesthetic obsession • velvet dreamer • never basic 💅 💎",
  "✨ Class and sass | heels devotee | 👠 living deluxe 🥂",
  "✨ Aesthetic obsession | black outfit lover | never basic 💅 🖤",
  "💄 Chic and classy | velvet dreamer | 🥂 living deluxe 🥂",
  "Living in style • fashion collector • never basic 💅 💎",
  "🖤 Dressed in confidence | perfume lover | 💄 high goals 👠",
  "🖤 Living in style | chic curator | 💅 effortlessly chic ✨",
  "✨ Styled with grace | perfume lover | 💎 never basic 💅",
  "🖤 Living in style | heels devotee | 👠 living deluxe 🥂",
  "💅 Chic and classy | heels devotee | 👠 effortlessly chic ✨",
  "Class and sass • fashion collector • pure luxury 💎 🖤",
  "👑 Living in style | makeup addict | high goals 👠 💅",
  "Chic and classy • red lip wearer • living deluxe 🥂 🥂",
  "👠 Class and sass | makeup addict | 🖤 high goals 👠",
  "💄 Chic and classy | red lip wearer | living deluxe 🥂 ✨",
  "👑 Golden energy | red lip wearer | ✨ effortlessly chic ✨",
  "💅 Aesthetic obsession | black outfit lover | living deluxe 🥂 💎",
  "👑 Aesthetic obsession | velvet dreamer | 💄 living deluxe 🥂",
  "👠 Main character vibes | black outfit lover | 🥂 high goals 👠",
  "Main character vibes • black outfit lover • living deluxe 🥂 ✨",
  "Dressed in confidence • red lip wearer • effortlessly chic ✨ ✨",
  "Styled with grace • red lip wearer • style speaks 💄 💎",
  "👑 Fashion enthusiast | makeup addict | 💄 high goals 👠",
  "👠 Golden energy | perfume lover | staying iconic 👑 💄",
  "💄 Golden energy | chic curator | living deluxe 🥂 👠",
  "💅 Golden energy | perfume lover | never basic 💅 🖤",
  "💎 Styled with grace | perfume lover | pure luxury 💎 👠",
  "💅 Golden energy | red lip wearer | staying iconic 👑 🖤",
  "Main character vibes • black outfit lover • living deluxe 🥂 👑",
  "💄 Living in style | makeup addict | 💎 high goals 👠",
  "Class and sass • fashion collector • high goals 👠 💎",
  "✨ Chic and classy | makeup addict | high goals 👠 👑",
  "💅 Living in style | heels devotee | 🖤 living deluxe 🥂",
  "🖤 Golden energy | red lip wearer | ✨ always polished 💍",
  "Golden energy • black outfit lover • living deluxe 🥂 👑",
  "Luxury mindset • chic curator • always polished 💍 👠",
];

export const VIP_BIOS = [
  "👑 VIP access only | 💎 Not everyone deserves my energy | ✨ I came, I saw, I conquered",
  "🌟 Limited edition human | 👑 Born to be extraordinary",
  "✨ Golden privileges | success builder | 🔐 first class moves 🌌",
  "⚜️ First class life | empire maker | invitation only 💎 💎",
  "💎 Premium membership | success builder | elite standard 🌟 🔐",
  "Untouchable lane • goal achiever • first class moves 🌌 💎",
  "🌌 Golden privileges | goal achiever | top level only ✨ 🔐",
  "⚜️ Royal entry | asset collector | invitation only 💎 🌟",
  "VIP standard • empire maker • VIP list only 👑 🌌",
  "Untouchable lane • goal achiever • top level only ✨ 👑",
  "👑 First class life | empire maker | first class moves 🌌 🥂",
  "🥂 Royal entry | leader always | VIP list only 👑 👑",
  "Untouchable lane • asset collector • elite standard 🌟 ✨",
  "🔐 Top tier human | empire maker | top level only ✨ 💎",
  "Top tier human • focus driver • access restricted 🔐 💎",
  "✨ Golden privileges | excellence driver | premium soul 💎 🌌",
  "Untouchable lane • success builder • first class moves 🌌 ✨",
  "Royal entry • excellence driver • top level only ✨ 👑",
  "🌟 Royal entry | goal achiever | access restricted 🔐 🌌",
  "🔐 Top tier human | strategic thinker | top level only ✨ 💎",
  "🥂 Exclusivity is key | leader always | ✨ invitation only 💎",
  "Selective circle • empire maker • VIP list only 👑 ✨",
  "🔐 Elite status | excellence driver | ✨ VIP list only 👑",
  "💎 Golden privileges | leader always | top level only ✨ ✨",
  "VIP standard • focus driver • premium soul 💎 🔐",
  "Premium membership • asset collector • elite standard 🌟 ✨",
  "🔐 First class life | empire maker | no cheap talk 🥂 🥂",
  "🔐 Untouchable lane | success builder | no cheap talk 🥂 🥂",
  "🌟 Premium membership | focus driver | 🥂 top level only ✨",
  "⚜️ Top tier human | success builder | 🔐 invitation only 💎",
  "VIP standard • focus driver • premium soul 💎 💎",
  "First class life • strategic thinker • access restricted 🔐 🔐",
  "Exclusivity is key • excellence driver • access restricted 🔐 👑",
  "Premium membership • success builder • elite standard 🌟 ⚜️",
  "⚜️ Royal entry | asset collector | first class moves 🌌 🥂",
  "💎 Exclusivity is key | success builder | first class moves 🌌 🥂",
  "Selective circle • excellence driver • premium soul 💎 🥂",
  "🔐 First class life | leader always | 👑 elite standard 🌟",
  "VIP standard • success builder • first class moves 🌌 💎",
  "First class life • focus driver • first class moves 🌌 💎",
  "💎 First class life | leader always | 🌌 invitation only 💎",
  "💎 Golden privileges | empire maker | ✨ invitation only 💎",
  "🌌 VIP standard | goal achiever | first class moves 🌌 🥂",
  "🌟 VIP standard | excellence driver | no cheap talk 🥂 🥂",
  "👑 Premium membership | strategic thinker | 🔐 VIP list only 👑",
  "🥂 Top tier human | leader always | invitation only 💎 ⚜️",
  "⚜️ Golden privileges | empire maker | 🌌 no cheap talk 🥂",
  "🌌 Exclusivity is key | asset collector | no cheap talk 🥂 ⚜️",
  "🌌 VIP standard | excellence driver | ✨ premium soul 💎",
  "Untouchable lane • leader always • invitation only 💎 🌟",
  "💎 Elite status | excellence driver | first class moves 🌌 🌌",
  "🥂 Top tier human | strategic thinker | premium soul 💎 ✨",
  "👑 Selective circle | excellence driver | first class moves 🌌 ✨",
  "Golden privileges • empire maker • no cheap talk 🥂 ✨",
  "💎 Selective circle | goal achiever | first class moves 🌌 🔐",
  "⚜️ Top tier human | goal achiever | 🥂 top level only ✨",
  "Exclusivity is key • excellence driver • access restricted 🔐 💎",
  "💎 Selective circle | focus driver | elite standard 🌟 🌌",
  "🌟 First class life | success builder | ✨ access restricted 🔐",
  "💎 Royal entry | excellence driver | ⚜️ VIP list only 👑",
  "Untouchable lane • goal achiever • no cheap talk 🥂 🥂",
  "✨ Elite status | empire maker | 🥂 no cheap talk 🥂",
  "Premium membership • empire maker • VIP list only 👑 👑",
  "Elite status • leader always • first class moves 🌌 🌌",
  "💎 Premium membership | empire maker | no cheap talk 🥂 🔐",
  "🥂 Elite status | empire maker | ⚜️ first class moves 🌌",
  "💎 Exclusivity is key | focus driver | invitation only 💎 ⚜️",
  "First class life • asset collector • access restricted 🔐 🌟",
  "🌌 First class life | leader always | 👑 premium soul 💎",
  "Selective circle • strategic thinker • first class moves 🌌 👑",
  "Premium membership • empire maker • elite standard 🌟 ✨",
  "⚜️ VIP standard | focus driver | 🔐 premium soul 💎",
  "💎 First class life | success builder | ✨ elite standard 🌟",
  "💎 Top tier human | strategic thinker | 🔐 first class moves 🌌",
  "✨ First class life | strategic thinker | 🥂 premium soul 💎",
  "👑 Exclusivity is key | empire maker | 🔐 premium soul 💎",
  "Golden privileges • strategic thinker • access restricted 🔐 💎",
  "🥂 Untouchable lane | focus driver | access restricted 🔐 ⚜️",
  "🔐 Top tier human | success builder | ✨ no cheap talk 🥂",
  "🔐 Elite status | focus driver | premium soul 💎 ⚜️",
  "✨ Royal entry | focus driver | 🔐 first class moves 🌌",
  "First class life • asset collector • VIP list only 👑 👑",
  "🌌 Untouchable lane | leader always | VIP list only 👑 ⚜️",
  "🌟 Royal entry | strategic thinker | premium soul 💎 💎",
  "⚜️ Premium membership | excellence driver | 💎 invitation only 💎",
  "🌌 VIP standard | empire maker | 🥂 VIP list only 👑",
  "💎 Top tier human | empire maker | no cheap talk 🥂 🌟",
  "🔐 Selective circle | excellence driver | ⚜️ access restricted 🔐",
  "🌌 Top tier human | success builder | ✨ VIP list only 👑",
  "Exclusivity is key • leader always • elite standard 🌟 💎",
  "🔐 Premium membership | excellence driver | 🥂 premium soul 💎",
  "✨ Royal entry | focus driver | invitation only 💎 👑",
  "🥂 Untouchable lane | focus driver | 🔐 top level only ✨",
  "💎 Selective circle | empire maker | top level only ✨ 🌌",
  "🌌 Untouchable lane | strategic thinker | 💎 invitation only 💎",
  "🔐 Top tier human | focus driver | invitation only 💎 👑",
  "🌟 Premium membership | goal achiever | ✨ top level only ✨",
  "🌌 Elite status | excellence driver | top level only ✨ ⚜️",
  "💎 Golden privileges | strategic thinker | premium soul 💎 👑",
  "Exclusivity is key • leader always • premium soul 💎 ⚜️",
];

export const ATTITUDE_BIOS = [
  "🔥 They said calm down. I said no | My energy is not for the faint-hearted",
  "⚡ I am not difficult, I just have standards",
  "🕶️ My vibe my style | standard speaker | unapologetic always ⚡ 😏",
  "👑 Attitude in my DNA | peace protector | unapologetic always ⚡ 🧿",
  "🖤 Unapologetic queen | truth talker | attitude speaks 🖤 ⚡",
  "Unapologetic queen • focus queen • my way or highway 👑 👑",
  "🖤 My vibe my style | hustler | 🧿 attitude speaks 🖤",
  "🧿 No fake smiles | truth talker | no fake vibes 🔥 🔥",
  "👑 Respect is earned | truth talker | attitude speaks 🖤 🕶️",
  "🧿 My rules my life | bound setter | 💪 watch me win 🖤",
  "🖤 My rules my life | peace protector | 💪 my way or highway 👑",
  "🔥 Attitude in my DNA | focus queen | unapologetic always ⚡ 😏",
  "My vibe my style • goal seeker • unapologetic always ⚡ 💪",
  "⚡ Bold decisions | truth talker | no fake vibes 🔥 🖤",
  "🕶️ Respect is earned | hustler | unapologetic always ⚡ 🖤",
  "🔥 My vibe my style | focus queen | 🖤 deal with it 🔥",
  "🖤 Attitude in my DNA | truth talker | 🕶️ watch me win 🖤",
  "💪 Attitude in my DNA | standard speaker | 🕶️ my way or highway 👑",
  "Bold decisions • truth talker • no fake vibes 🔥 🧿",
  "💪 Attitude in my DNA | peace protector | 🔥 my way or highway 👑",
  "🔥 No fake smiles | bound setter | attitude speaks 🖤 🧿",
  "👑 Bold decisions | focus queen | 🔥 respect first 👑",
  "Zero filter • goal seeker • deal with it 🔥 🧿",
  "😏 Fierce and free | focus queen | 🧿 attitude speaks 🖤",
  "🕶️ My rules my life | standard speaker | 🧿 attitude speaks 🖤",
  "🧿 Respect is earned | hustler | 🕶️ respect first 👑",
  "👑 Attitude in my DNA | bound setter | 💪 watch me win 🖤",
  "💪 Unapologetic queen | goal seeker | 👑 no fake vibes 🔥",
  "No fake smiles • hustler • watch me win 🖤 🕶️",
  "Zero filter • focus queen • my way or highway 👑 🕶️",
  "🕶️ My rules my life | bound setter | 🧿 mind your business ⚡",
  "👑 Unapologetic queen | truth talker | 💪 attitude speaks 🖤",
  "👑 Unapologetic queen | standard speaker | 🔥 mind your business ⚡",
  "Bold decisions • goal seeker • attitude speaks 🖤 🔥",
  "🖤 Attitude in my DNA | truth talker | 🔥 mind your business ⚡",
  "Fierce and free • focus queen • watch me win 🖤 🧿",
  "⚡ Attitude in my DNA | bound setter | 👑 deal with it 🔥",
  "My rules my life • standard speaker • my way or highway 👑 🖤",
  "🔥 No fake smiles | standard speaker | 💪 no fake vibes 🔥",
  "💪 My vibe my style | peace protector | 🧿 unapologetic always ⚡",
  "🧿 Bold decisions | truth talker | respect first 👑 💪",
  "🧿 Zero filter | hustler | 💪 respect first 👑",
  "💪 Fierce and free | drama hater | unapologetic always ⚡ 👑",
  "My vibe my style • focus queen • my way or highway 👑 🕶️",
  "🧿 Zero filter | standard speaker | respect first 👑 🕶️",
  "My rules my life • bound setter • my way or highway 👑 👑",
  "💪 Attitude in my DNA | bound setter | 🕶️ deal with it 🔥",
  "🧿 Independent soul | drama hater | mind your business ⚡ 💪",
  "💪 Respect is earned | bound setter | 🕶️ mind your business ⚡",
  "Independent soul • goal seeker • respect first 👑 🧿",
  "🧿 My vibe my style | hustler | my way or highway 👑 👑",
  "🕶️ My vibe my style | peace protector | ⚡ watch me win 🖤",
  "🖤 Zero filter | drama hater | 🕶️ attitude speaks 🖤",
  "🧿 No fake smiles | peace protector | ⚡ attitude speaks 🖤",
  "No fake smiles • drama hater • watch me win 🖤 🖤",
  "My vibe my style • drama hater • watch me win 🖤 💪",
  "Unapologetic queen • drama hater • attitude speaks 🖤 ⚡",
  "⚡ Attitude in my DNA | peace protector | deal with it 🔥 🧿",
  "Unapologetic queen • focus queen • respect first 👑 🖤",
  "😏 Respect is earned | truth talker | ⚡ my way or highway 👑",
  "⚡ Bold decisions | standard speaker | 🖤 unapologetic always ⚡",
  "Respect is earned • standard speaker • attitude speaks 🖤 🔥",
  "Bold decisions • focus queen • my way or highway 👑 👑",
  "⚡ Fierce and free | bound setter | 🔥 attitude speaks 🖤",
  "👑 Respect is earned | drama hater | attitude speaks 🖤 ⚡",
  "🔥 My vibe my style | drama hater | 👑 watch me win 🖤",
  "👑 My rules my life | focus queen | watch me win 🖤 🔥",
  "Bold decisions • bound setter • attitude speaks 🖤 🕶️",
  "💪 Fierce and free | goal seeker | 🔥 my way or highway 👑",
  "My vibe my style • standard speaker • my way or highway 👑 🧿",
  "Respect is earned • hustler • my way or highway 👑 😏",
  "👑 Respect is earned | standard speaker | 💪 watch me win 🖤",
  "Fierce and free • truth talker • deal with it 🔥 😏",
  "Independent soul • bound setter • attitude speaks 🖤 🕶️",
  "Attitude in my DNA • peace protector • attitude speaks 🖤 🔥",
  "👑 My vibe my style | drama hater | mind your business ⚡ 🧿",
  "👑 Attitude in my DNA | bound setter | ⚡ deal with it 🔥",
  "😏 No fake smiles | goal seeker | 👑 attitude speaks 🖤",
  "Attitude in my DNA • bound setter • my way or highway 👑 🧿",
  "🧿 Unapologetic queen | hustler | ⚡ watch me win 🖤",
  "🕶️ No fake smiles | hustler | attitude speaks 🖤 😏",
  "🔥 My vibe my style | goal seeker | 💪 respect first 👑",
  "My vibe my style • focus queen • no fake vibes 🔥 🖤",
  "Independent soul • focus queen • attitude speaks 🖤 🧿",
  "🖤 No fake smiles | truth talker | watch me win 🖤 🕶️",
  "🔥 Fierce and free | truth talker | ⚡ respect first 👑",
  "🖤 My rules my life | drama hater | my way or highway 👑 👑",
  "🧿 Fierce and free | drama hater | attitude speaks 🖤 🕶️",
  "🔥 My vibe my style | truth talker | watch me win 🖤 😏",
  "🔥 My rules my life | bound setter | no fake vibes 🔥 😏",
  "Zero filter • peace protector • respect first 👑 👑",
  "Unapologetic queen • focus queen • mind your business ⚡ 🕶️",
  "💪 My vibe my style | goal seeker | ⚡ attitude speaks 🖤",
  "😏 My rules my life | peace protector | my way or highway 👑 🧿",
  "🧿 My rules my life | standard speaker | 😏 mind your business ⚡",
  "Attitude in my DNA • peace protector • deal with it 🔥 👑",
  "My rules my life • peace protector • no fake vibes 🔥 🔥",
  "My rules my life • goal seeker • respect first 👑 😏",
  "🕶️ Fierce and free | goal seeker | 😏 my way or highway 👑",
  "Fierce and free • peace protector • unapologetic always ⚡ 🔥",
];

export const AESTHETIC_BIOS = [
  "🌙 She lives in poems no one reads | 🌫️ Breathing fog, chasing light",
  "🕯️ Dark academia heart | 📚 Old books & older souls",
  "🎞️ Ethereal dreams | poetry writer | slow and simple 🌿 ☁️",
  "🪐 Slow living advocate | story teller | ☁️ finding beauty 🌻",
  "🎞️ Dark academia vibe | canvas painter | 🕯️ star dust vibes ✨",
  "🕯️ Slow living advocate | candle lighter | living ethereal 🌙 🎨",
  "☁️ Dark academia vibe | museum walker | dreamy aesthetic ☁️ 🕯️",
  "☁️ Living in poems | matcha drinker | finding beauty 🌻 🎨",
  "🎞️ Celestial traveller | poetry writer | 🌸 star dust vibes ✨",
  "Art in my veins • canvas painter • living ethereal 🌙 🌙",
  "Art in my veins • poetry writer • slow and simple 🌿 🎞️",
  "🪐 Dark academia vibe | canvas painter | 🌿 living ethereal 🌙",
  "🎨 Dark academia vibe | museum walker | star dust vibes ✨ 🌸",
  "Stardust soul • museum walker • dreamy aesthetic ☁️ 🎨",
  "🎨 Cottagecore lover | poetry writer | 🪐 slow and simple 🌿",
  "Cottagecore lover • candle lighter • finding beauty 🌻 🕯️",
  "Living in poems • canvas painter • slow and simple 🌿 🎞️",
  "🎨 Vintage heart | canvas painter | ☁️ star dust vibes ✨",
  "Ethereal dreams • story teller • slow and simple 🌿 🌿",
  "Slow living advocate • story teller • vintage soul 🎞️ ☁️",
  "🪐 Dark academia vibe | wildflower picker | 🌿 living ethereal 🌙",
  "Art in my veins • vinyl listener • finding beauty 🌻 🪐",
  "🌿 Stardust soul | canvas painter | finding beauty 🌻 🎨",
  "Slow living advocate • museum walker • dreamy aesthetic ☁️ 🎞️",
  "Cloud catcher • story teller • dreamy aesthetic ☁️ 🎞️",
  "🪐 Art in my veins | poetry writer | living ethereal 🌙 ☁️",
  "☁️ Cloud catcher | vinyl listener | dreamy aesthetic ☁️ 🎞️",
  "Living in poems • poetry writer • cozy vibes 🕯️ 🪐",
  "Dark academia vibe • story teller • star dust vibes ✨ ☁️",
  "Stardust soul • matcha drinker • dreamy aesthetic ☁️ 🕯️",
  "Slow living advocate • wildflower picker • finding beauty 🌻 🪐",
  "🌸 Cottagecore lover | poetry writer | finding beauty 🌻 ☁️",
  "🌙 Slow living advocate | vinyl listener | ☁️ living ethereal 🌙",
  "🌿 Stardust soul | museum walker | ☁️ vintage soul 🎞️",
  "🎞️ Dark academia vibe | story teller | vintage soul 🎞️ 🌿",
  "🪐 Dark academia vibe | canvas painter | 🌸 in soft colors 🌸",
  "🪐 Dark academia vibe | canvas painter | 🎨 in soft colors 🌸",
  "Stardust soul • poetry writer • star dust vibes ✨ ☁️",
  "☁️ Stardust soul | matcha drinker | 🎞️ finding beauty 🌻",
  "☁️ Dark academia vibe | poetry writer | 🌸 slow and simple 🌿",
  "🌿 Celestial traveller | matcha drinker | living ethereal 🌙 ☁️",
  "🌿 Ethereal dreams | matcha drinker | ☁️ living ethereal 🌙",
  "Celestial traveller • canvas painter • dreamy aesthetic ☁️ 🌿",
  "Celestial traveller • story teller • star dust vibes ✨ 🌿",
  "Celestial traveller • museum walker • slow and simple 🌿 🌸",
  "🪐 Living in poems | story teller | 🎞️ star dust vibes ✨",
  "🌸 Art in my veins | story teller | 🎞️ dreamy aesthetic ☁️",
  "🕯️ Cottagecore lover | story teller | star dust vibes ✨ 🌙",
  "🪐 Slow living advocate | vinyl listener | cozy vibes 🕯️ 🎨",
  "🕯️ Cottagecore lover | story teller | 🎨 living ethereal 🌙",
  "🪐 Vintage heart | vinyl listener | finding beauty 🌻 🎞️",
  "Ethereal dreams • matcha drinker • in soft colors 🌸 🌸",
  "🪐 Stardust soul | story teller | ☁️ living ethereal 🌙",
  "🌿 Cloud catcher | canvas painter | star dust vibes ✨ 🪐",
  "🌿 Living in poems | wildflower picker | ☁️ cozy vibes 🕯️",
  "Slow living advocate • matcha drinker • cozy vibes 🕯️ 🕯️",
  "🌿 Living in poems | matcha drinker | star dust vibes ✨ 🪐",
  "🌸 Vintage heart | candle lighter | 🌿 dreamy aesthetic ☁️",
  "🌸 Slow living advocate | canvas painter | 🕯️ dreamy aesthetic ☁️",
  "Stardust soul • canvas painter • cozy vibes 🕯️ ☁️",
  "🌸 Vintage heart | vinyl listener | living ethereal 🌙 ☁️",
  "Art in my veins • canvas painter • vintage soul 🎞️ 🎞️",
  "☁️ Slow living advocate | wildflower picker | 🌿 cozy vibes 🕯️",
  "🌙 Cottagecore lover | wildflower picker | 🕯️ in soft colors 🌸",
  "Cottagecore lover • vinyl listener • living ethereal 🌙 🌿",
  "🌿 Living in poems | canvas painter | vintage soul 🎞️ 🎨",
  "Slow living advocate • poetry writer • slow and simple 🌿 🎨",
  "Celestial traveller • vinyl listener • dreamy aesthetic ☁️ 🎨",
  "🪐 Stardust soul | poetry writer | in soft colors 🌸 🌸",
  "🌙 Celestial traveller | candle lighter | finding beauty 🌻 ☁️",
  "Dark academia vibe • museum walker • finding beauty 🌻 🕯️",
  "☁️ Stardust soul | poetry writer | living ethereal 🌙 🎨",
  "🕯️ Dark academia vibe | museum walker | 🌙 star dust vibes ✨",
  "Celestial traveller • story teller • slow and simple 🌿 🪐",
  "🕯️ Cloud catcher | story teller | vintage soul 🎞️ 🌿",
  "🎞️ Cloud catcher | canvas painter | slow and simple 🌿 ☁️",
  "🪐 Ethereal dreams | matcha drinker | 🎨 living ethereal 🌙",
  "Living in poems • matcha drinker • vintage soul 🎞️ 🪐",
  "🎞️ Living in poems | candle lighter | finding beauty 🌻 🕯️",
  "Cottagecore lover • poetry writer • in soft colors 🌸 ☁️",
  "🌿 Cloud catcher | canvas painter | slow and simple 🌿 🌸",
  "🎨 Living in poems | poetry writer | in soft colors 🌸 🪐",
  "🎞️ Living in poems | canvas painter | 🕯️ cozy vibes 🕯️",
  "🕯️ Art in my veins | museum walker | cozy vibes 🕯️ 🎨",
  "☁️ Art in my veins | candle lighter | 🎞️ star dust vibes ✨",
  "🪐 Stardust soul | matcha drinker | dreamy aesthetic ☁️ 🌙",
  "Stardust soul • canvas painter • living ethereal 🌙 🌸",
  "🌿 Celestial traveller | poetry writer | in soft colors 🌸 🌙",
  "🌿 Cottagecore lover | wildflower picker | cozy vibes 🕯️ ☁️",
  "Slow living advocate • poetry writer • in soft colors 🌸 ☁️",
  "Art in my veins • poetry writer • cozy vibes 🕯️ 🕯️",
  "Art in my veins • wildflower picker • in soft colors 🌸 🌸",
  "🕯️ Celestial traveller | matcha drinker | 🪐 living ethereal 🌙",
  "🌙 Art in my veins | vinyl listener | in soft colors 🌸 🪐",
  "🌿 Cottagecore lover | wildflower picker | 🌙 dreamy aesthetic ☁️",
  "🪐 Dark academia vibe | candle lighter | 🎞️ slow and simple 🌿",
  "☁️ Vintage heart | matcha drinker | 🕯️ living ethereal 🌙",
  "🌙 Living in poems | museum walker | vintage soul 🎞️ 🎞️",
  "☁️ Cottagecore lover | matcha drinker | 🕯️ cozy vibes 🕯️",
  "🪐 Cottagecore lover | vinyl listener | 🎨 slow and simple 🌿",
];

export const SAVAGE_BIOS = [
  "😏 Sorry, were you talking? I was busy not caring | 🔥 Savage but right",
  "💅 My patience is not endless. Neither is my kindness",
  "👑 Not your baby | standard keeper | too busy winning 🔥 💸",
  "😏 Your loss, not mine | standard keeper | keep scrolling 🖤 💋",
  "👑 Sweet but savage | queen bee | 😏 cry about it 😏",
  "Classy with attitude • dream chaser • blocked and blessed 💅 🖤",
  "🔥 Sassy since birth | money maker | not your level 👑 😏",
  "💸 Your loss, not mine | independent boss | 🔥 savage and proud ⚡",
  "Too hot to handle • money maker • watch the glow 😏 🔥",
  "Savage queen • standard keeper • not your level 👑 ⚡",
  "⚡ Spitting facts only | queen bee | too busy winning 🔥 🖤",
  "💅 Sweet but savage | money maker | blocked and blessed 💅 🔥",
  "💋 Ice cold heart | game winner | 🔥 savage and proud ⚡",
  "Spitting facts only • standard keeper • too busy winning 🔥 ⚡",
  "⚡ Too hot to handle | shade thrower | keep scrolling 🖤 😏",
  "Spitting facts only • money maker • blocked and blessed 💅 🖤",
  "⚡ Your loss, not mine | success stacker | not your level 👑 💅",
  "🔥 Classy with attitude | game winner | no discount 🔥 💸",
  "😏 Savage queen | shade thrower | cry about it 😏 🖤",
  "🔥 Sweet but savage | independent boss | savage and proud ⚡ ⚡",
  "💸 Sassy since birth | shade thrower | no discount 🔥 💅",
  "💸 Spitting facts only | shade thrower | cry about it 😏 😏",
  "Highly requested • independent boss • watch the glow 😏 💸",
  "Classy with attitude • money maker • savage and proud ⚡ 🖤",
  "😏 Not your baby | game winner | 🖤 keep scrolling 🖤",
  "💸 Not your baby | game winner | watch the glow 😏 😏",
  "💋 Not your baby | independent boss | 🖤 keep scrolling 🖤",
  "Your loss, not mine • standard keeper • cry about it 😏 💋",
  "Your loss, not mine • game winner • savage and proud ⚡ 👑",
  "Savage queen • success stacker • savage and proud ⚡ 🖤",
  "🖤 Sassy since birth | game winner | savage and proud ⚡ 💅",
  "😏 Sweet but savage | standard keeper | 🖤 not your level 👑",
  "💅 Classy with attitude | queen bee | 🖤 keep scrolling 🖤",
  "👑 Spitting facts only | queen bee | 💅 cry about it 😏",
  "💅 Sweet but savage | game winner | not your level 👑 💸",
  "🖤 Too hot to handle | success stacker | 😏 no discount 🔥",
  "Ice cold heart • success stacker • savage and proud ⚡ 🖤",
  "😏 Savage queen | queen bee | 💅 cry about it 😏",
  "🔥 Savage queen | shade thrower | 👑 savage and proud ⚡",
  "⚡ Classy with attitude | shade thrower | savage and proud ⚡ 👑",
  "👑 Savage queen | independent boss | 💅 too busy winning 🔥",
  "Your loss, not mine • queen bee • no discount 🔥 💅",
  "😏 Not your baby | money maker | 💋 keep scrolling 🖤",
  "Sassy since birth • money maker • savage and proud ⚡ 🖤",
  "Savage queen • queen bee • blocked and blessed 💅 🖤",
  "Savage queen • shade thrower • savage and proud ⚡ 💸",
  "👑 Sweet but savage | standard keeper | blocked and blessed 💅 ⚡",
  "💸 Sassy since birth | success stacker | watch the glow 😏 💋",
  "👑 Classy with attitude | game winner | watch the glow 😏 💋",
  "💸 Ice cold heart | standard keeper | keep scrolling 🖤 🔥",
  "⚡ Not your baby | success stacker | savage and proud ⚡ 🔥",
  "💅 Spitting facts only | money maker | 🔥 watch the glow 😏",
  "😏 Too hot to handle | queen bee | 💋 too busy winning 🔥",
  "Savage queen • independent boss • keep scrolling 🖤 😏",
  "⚡ Sweet but savage | standard keeper | watch the glow 😏 🖤",
  "Sassy since birth • independent boss • too busy winning 🔥 💅",
  "⚡ Sassy since birth | independent boss | blocked and blessed 💅 💸",
  "💅 Too hot to handle | success stacker | no discount 🔥 ⚡",
  "Ice cold heart • shade thrower • not your level 👑 💋",
  "Not your baby • shade thrower • watch the glow 😏 💅",
  "Spitting facts only • money maker • too busy winning 🔥 😏",
  "⚡ Ice cold heart | dream chaser | no discount 🔥 😏",
  "💋 Too hot to handle | shade thrower | 🖤 savage and proud ⚡",
  "Sassy since birth • independent boss • watch the glow 😏 💸",
  "😏 Not your baby | shade thrower | watch the glow 😏 💅",
  "🖤 Ice cold heart | money maker | keep scrolling 🖤 💅",
  "🖤 Classy with attitude | shade thrower | 💅 watch the glow 😏",
  "🔥 Not your baby | queen bee | 💋 blocked and blessed 💅",
  "💸 Classy with attitude | queen bee | 😏 not your level 👑",
  "💋 Highly requested | independent boss | blocked and blessed 💅 💅",
  "🔥 Highly requested | shade thrower | ⚡ blocked and blessed 💅",
  "💋 Spitting facts only | independent boss | 💸 not your level 👑",
  "Highly requested • game winner • cry about it 😏 💅",
  "💋 Savage queen | independent boss | 👑 cry about it 😏",
  "⚡ Sweet but savage | success stacker | too busy winning 🔥 👑",
  "⚡ Spitting facts only | dream chaser | 💸 not your level 👑",
  "Too hot to handle • standard keeper • keep scrolling 🖤 ⚡",
  "🖤 Not your baby | independent boss | blocked and blessed 💅 💸",
  "😏 Classy with attitude | game winner | savage and proud ⚡ 💅",
  "😏 Not your baby | independent boss | keep scrolling 🖤 💅",
  "😏 Sweet but savage | success stacker | no discount 🔥 💸",
  "👑 Spitting facts only | standard keeper | 💸 not your level 👑",
  "Classy with attitude • shade thrower • cry about it 😏 🖤",
  "Highly requested • game winner • keep scrolling 🖤 💸",
  "Savage queen • dream chaser • blocked and blessed 💅 ⚡",
  "🖤 Sassy since birth | money maker | ⚡ no discount 🔥",
  "💸 Classy with attitude | success stacker | 💅 cry about it 😏",
  "Savage queen • success stacker • no discount 🔥 ⚡",
  "Spitting facts only • game winner • not your level 👑 🖤",
  "😏 Your loss, not mine | independent boss | 👑 blocked and blessed 💅",
  "🔥 Highly requested | dream chaser | not your level 👑 💸",
  "⚡ Spitting facts only | dream chaser | savage and proud ⚡ 🖤",
  "💋 Your loss, not mine | standard keeper | 👑 cry about it 😏",
  "Savage queen • success stacker • too busy winning 🔥 ⚡",
  "👑 Classy with attitude | success stacker | 🖤 no discount 🔥",
  "⚡ Your loss, not mine | game winner | 💅 savage and proud ⚡",
  "🔥 Your loss, not mine | money maker | not your level 👑 💸",
  "Not your baby • money maker • savage and proud ⚡ 🔥",
  "👑 Sweet but savage | dream chaser | ⚡ watch the glow 😏",
  "💸 Not your baby | game winner | 😏 blocked and blessed 💅",
];

export const EMOTIONAL_BIOS = [
  "💔 Smiling because I have to, healing because I choose to | 🌧️ Storms pass",
  "🌧️ She carries storms in her chest | 💔 But lightning in her spine",
  "🕯️ Guard your peace | self healer | 🌧️ learning to love me 🕯️",
  "💔 Under reconstruction | poetry reader | moving forward 🌿 🍂",
  "Quiet storm inside • dream keeper • moving forward 🌿 🌙",
  "Soft heart strong mind • self healer • learning to love me 🕯️ 🌸",
  "🕊️ Healing in silence | peace seeker | learning to love me 🕯️ 🕯️",
  "🌧️ Guard your peace | hope believer | 🍂 learning to love me 🕯️",
  "Under reconstruction • sunset watcher • moving forward 🌿 ✨",
  "Healing in silence • peace seeker • stronger today 🌅 🌸",
  "💔 Learning to let go | pain survivor | healing daily ✨ 🕯️",
  "🌧️ Scars tell stories | poetry reader | ✨ finding peace 🕊️",
  "Guard your peace • poetry reader • finding peace 🕊️ 🌧️",
  "Feeling everything • moon lover • heart of hope 💫 ✨",
  "🍂 Finding my light | dream keeper | stronger today 🌅 ✨",
  "🕯️ Quiet storm inside | pain survivor | 💔 finding peace 🕊️",
  "Learning to let go • hope believer • still blooming 🌸 🌸",
  "🌧️ Feeling everything | peace seeker | healing daily ✨ 💔",
  "✨ Beautifully broken | sunset watcher | 🌧️ learning to love me 🕯️",
  "Feeling everything • moon lover • finding peace 🕊️ 🕯️",
  "🍂 Under reconstruction | self healer | storms pass 🌧️ ✨",
  "🌧️ Learning to let go | self healer | storms pass 🌧️ 🌙",
  "🕯️ Guard your peace | pain survivor | 🌸 storms pass 🌧️",
  "💔 Under reconstruction | poetry reader | finding peace 🕊️ 🌙",
  "💔 Finding my light | dream keeper | stronger today 🌅 🌧️",
  "🌧️ Guard your peace | moon lover | 🕊️ finding peace 🕊️",
  "🕊️ Quiet storm inside | moon lover | storms pass 🌧️ 🌙",
  "🕊️ Beautifully broken | hope believer | 🌸 healing daily ✨",
  "🌧️ Scars tell stories | sunset watcher | still blooming 🌸 💔",
  "🌸 Soft heart strong mind | hope believer | 🌙 heart of hope 💫",
  "🌸 Feeling everything | self healer | heart of hope 💫 🍂",
  "🕊️ Under reconstruction | sunset watcher | ✨ learning to love me 🕯️",
  "🌧️ Finding my light | sunset watcher | 🍂 finding peace 🕊️",
  "✨ Healing in silence | hope believer | 🌙 still blooming 🌸",
  "🌸 Finding my light | hope believer | 💔 moving forward 🌿",
  "Soft heart strong mind • moon lover • learning to love me 🕯️ 🌧️",
  "🌸 Healing in silence | self healer | 💔 storms pass 🌧️",
  "🌧️ Learning to let go | pain survivor | ✨ heart of hope 💫",
  "✨ Quiet storm inside | moon lover | 🍂 heart of hope 💫",
  "Guard your peace • peace seeker • healing daily ✨ 🍂",
  "✨ Feeling everything | peace seeker | stronger today 🌅 🕯️",
  "Finding my light • moon lover • learning to love me 🕯️ 🌧️",
  "Scars tell stories • self healer • learning to love me 🕯️ 💔",
  "🌧️ Under reconstruction | peace seeker | 🕊️ healing daily ✨",
  "🌸 Learning to let go | pain survivor | learning to love me 🕯️ 💔",
  "🌸 Finding my light | dream keeper | learning to love me 🕯️ 🌙",
  "🌸 Beautifully broken | pain survivor | 🕊️ healing daily ✨",
  "Learning to let go • dream keeper • still blooming 🌸 💔",
  "🕊️ Soft heart strong mind | sunset watcher | still blooming 🌸 🕯️",
  "🌙 Beautifully broken | sunset watcher | 🕯️ stronger today 🌅",
  "Scars tell stories • self healer • moving forward 🌿 💔",
  "💔 Finding my light | hope believer | ✨ learning to love me 🕯️",
  "Finding my light • hope believer • finding peace 🕊️ 🍂",
  "Guard your peace • dream keeper • moving forward 🌿 ✨",
  "🌙 Under reconstruction | dream keeper | storms pass 🌧️ 🍂",
  "🕯️ Under reconstruction | poetry reader | 🕊️ heart of hope 💫",
  "Scars tell stories • hope believer • finding peace 🕊️ 🌸",
  "🕊️ Learning to let go | moon lover | moving forward 🌿 ✨",
  "✨ Learning to let go | self healer | healing daily ✨ 🍂",
  "🍂 Healing in silence | pain survivor | 🕊️ storms pass 🌧️",
  "🕊️ Feeling everything | hope believer | 🕯️ healing daily ✨",
  "🌧️ Healing in silence | dream keeper | 🕯️ learning to love me 🕯️",
  "Learning to let go • sunset watcher • stronger today 🌅 🕊️",
  "💔 Under reconstruction | sunset watcher | heart of hope 💫 🕊️",
  "🌸 Guard your peace | moon lover | 🕯️ stronger today 🌅",
  "🍂 Quiet storm inside | poetry reader | learning to love me 🕯️ 🌧️",
  "Soft heart strong mind • self healer • moving forward 🌿 💔",
  "🍂 Learning to let go | poetry reader | finding peace 🕊️ 🕊️",
  "Scars tell stories • moon lover • finding peace 🕊️ 💔",
  "🌙 Guard your peace | peace seeker | storms pass 🌧️ 🌸",
  "Scars tell stories • pain survivor • finding peace 🕊️ 🌧️",
  "🌸 Learning to let go | sunset watcher | still blooming 🌸 🕯️",
  "🕊️ Scars tell stories | dream keeper | 🕯️ heart of hope 💫",
  "Learning to let go • moon lover • healing daily ✨ 🌧️",
  "🌸 Quiet storm inside | pain survivor | healing daily ✨ ✨",
  "💔 Under reconstruction | poetry reader | 🌸 storms pass 🌧️",
  "💔 Learning to let go | moon lover | 🕊️ learning to love me 🕯️",
  "🌧️ Quiet storm inside | dream keeper | 🍂 still blooming 🌸",
  "🕯️ Learning to let go | peace seeker | still blooming 🌸 ✨",
  "Quiet storm inside • sunset watcher • still blooming 🌸 🍂",
  "🌧️ Scars tell stories | peace seeker | still blooming 🌸 💔",
  "Feeling everything • self healer • stronger today 🌅 🕊️",
  "Finding my light • sunset watcher • moving forward 🌿 🌸",
  "Beautifully broken • peace seeker • still blooming 🌸 💔",
  "Learning to let go • self healer • storms pass 🌧️ 🕊️",
  "💔 Finding my light | sunset watcher | moving forward 🌿 🌙",
  "✨ Learning to let go | pain survivor | 🕊️ finding peace 🕊️",
  "💔 Soft heart strong mind | poetry reader | heart of hope 💫 🍂",
  "🌧️ Healing in silence | peace seeker | moving forward 🌿 🕊️",
  "🍂 Scars tell stories | pain survivor | 🕯️ moving forward 🌿",
  "🍂 Feeling everything | pain survivor | 💔 still blooming 🌸",
  "🌧️ Finding my light | self healer | storms pass 🌧️ 🕊️",
  "🌸 Quiet storm inside | moon lover | 🍂 heart of hope 💫",
  "Quiet storm inside • self healer • storms pass 🌧️ 🌧️",
  "🕊️ Finding my light | moon lover | 🍂 heart of hope 💫",
  "✨ Guard your peace | dream keeper | heart of hope 💫 🍂",
  "Scars tell stories • pain survivor • stronger today 🌅 ✨",
  "Soft heart strong mind • dream keeper • learning to love me 🕯️ 🌙",
  "🌧️ Finding my light | self healer | finding peace 🕊️ 🕊️",
  "🌧️ Learning to let go | pain survivor | 💔 storms pass 🌧️",
];

export const SHORT_BIOS = [
  "✨ Soft heart. Strong mind. Bold soul.",
  "👑 Queen with dreams | Building my empire",
  "🖤 Fearless | and gold | ✨ glow 💫",
  "💅 Iconic | and blessed | vibe ⚡ 🌿",
  "Pure gold • and wild • hustle 💪 👑",
  "🌸 Fearless | and rare | glow 💫 💪",
  "💅 Dreaming | and wild | hustle 💪 ✨",
  "⚡ Unique | and rare | soul ✨ 💅",
  "Authentic • and rare • peace 🕊️ 💅",
  "💅 Royalty | and bold | 👑 queen 👑",
  "🌸 Iconic | and strong | 🌿 glow 💫",
  "Self-made • and real • glow 💫 👑",
  "Rare breed • and gold • mind 🧠 💅",
  "🌸 Fearless | and wild | hustle 💪 🖤",
  "🌸 Iconic | and rare | 💅 vibe ⚡",
  "Slaying • and rare • dream 🌙 💅",
  "🌸 Unique | and blessed | heart 🌸 🌿",
  "🌸 Rare breed | and bold | ✨ vibe ⚡",
  "⚡ Blessed | and bold | 🌸 vibe ⚡",
  "Self-made • and bold • babe 💅 👑",
  "🖤 Unique | and blessed | 🌿 vibe ⚡",
  "⚡ Blessed | and wild | 🌸 glow 💫",
  "Unbothered • and blessed • glow 💫 👑",
  "✨ Self-made | and wild | 🖤 soul ✨",
  "Classic • and wild • glow 💫 👑",
  "💪 Authentic | and free | 🌸 soul ✨",
  "🌿 Fearless | and gold | peace 🕊️ 💅",
  "🌿 Classic | and rare | 💅 hustle 💪",
  "⚡ Slaying | and gold | vibe ⚡ 💪",
  "🌿 Unstoppable | and strong | glow 💫 ⚡",
  "Fearless • and bold • glow 💫 👑",
  "💅 Free spirit | and real | dream 🌙 👑",
  "🌿 Classic | and strong | 💅 babe 💅",
  "🌿 Iconic | and gold | heart 🌸 💪",
  "⚡ Wildflower | and blessed | 💅 babe 💅",
  "🖤 Self-made | and wild | 💪 soul ✨",
  "🌿 Dreaming | and free | 💅 heart 🌸",
  "✨ Authentic | and wild | dream 🌙 👑",
  "👑 Unique | and gold | soul ✨ ⚡",
  "Wildflower • and free • glow 💫 ✨",
  "💪 Pure gold | and bold | vibe ⚡ ✨",
  "🖤 Pure gold | and rare | 🌸 queen 👑",
  "✨ Authentic | and real | heart 🌸 🌸",
  "🌿 Iconic | and gold | 🖤 mind 🧠",
  "Fearless • and free • soul ✨ ⚡",
  "Iconic • and rare • glow 💫 🖤",
  "🌿 Fearless | and strong | 👑 vibe ⚡",
  "👑 Unstoppable | and strong | ⚡ mind 🧠",
  "Iconic • and blessed • dream 🌙 💪",
  "✨ Royalty | and blessed | glow 💫 💪",
  "Iconic • and free • dream 🌙 🖤",
  "🖤 Wildflower | and bold | babe 💅 ⚡",
  "Self-made • and real • soul ✨ 🌸",
  "⚡ Wildflower | and rare | 🌸 glow 💫",
  "🖤 Free spirit | and blessed | heart 🌸 ⚡",
  "💅 Rare breed | and rare | heart 🌸 🌸",
  "Slaying • and free • hustle 💪 ✨",
  "⚡ Unbothered | and blessed | glow 💫 💪",
  "🌸 Iconic | and gold | ✨ heart 🌸",
  "Classic • and blessed • peace 🕊️ ✨",
  "💪 Dreaming | and blessed | 💅 soul ✨",
  "Fearless • and bold • heart 🌸 🌿",
  "Wildflower • and strong • vibe ⚡ ⚡",
  "Unique • and real • mind 🧠 🌸",
  "Free spirit • and gold • mind 🧠 💅",
  "🌸 Royalty | and wild | glow 💫 🖤",
  "🌿 Iconic | and rare | peace 🕊️ 🖤",
  "Blessed • and blessed • queen 👑 🌸",
  "Blessed • and real • hustle 💪 ⚡",
  "Slaying • and wild • queen 👑 🖤",
  "Slaying • and blessed • mind 🧠 ⚡",
  "Iconic • and real • queen 👑 🌿",
  "💅 Free spirit | and wild | 💪 babe 💅",
  "⚡ Royalty | and free | 💪 dream 🌙",
  "🌿 Blessed | and wild | mind 🧠 👑",
  "💅 Dreaming | and real | ⚡ heart 🌸",
  "💪 Iconic | and gold | 💅 babe 💅",
  "🌸 Royalty | and gold | vibe ⚡ ✨",
  "Rare breed • and strong • soul ✨ 🖤",
  "💪 Slaying | and free | soul ✨ ✨",
  "⚡ Self-made | and free | soul ✨ 🌸",
  "Self-made • and strong • heart 🌸 🖤",
  "🌸 Blessed | and wild | peace 🕊️ ✨",
  "💪 Wildflower | and real | ⚡ hustle 💪",
  "🌸 Royalty | and wild | 💪 peace 🕊️",
  "💪 Classic | and strong | mind 🧠 🖤",
  "🌿 Royalty | and strong | mind 🧠 ⚡",
  "Pure gold • and bold • queen 👑 🌸",
  "💪 Unique | and bold | hustle 💪 ⚡",
  "🖤 Classic | and strong | ✨ glow 💫",
  "🌿 Wildflower | and rare | dream 🌙 🖤",
  "Self-made • and gold • heart 🌸 ⚡",
  "⚡ Rare breed | and strong | babe 💅 🌿",
  "⚡ Unstoppable | and wild | 👑 vibe ⚡",
  "Royalty • and blessed • babe 💅 💪",
  "✨ Fearless | and wild | queen 👑 🌸",
  "💪 Pure gold | and strong | vibe ⚡ ✨",
  "Unstoppable • and wild • queen 👑 💪",
  "💅 Classic | and strong | 💪 hustle 💪",
  "Authentic • and real • soul ✨ 🌸",
];

export const EMOJI_BIOS = [
  "🌸✨🌙 soft | dreamy | magical | blooming every day 💕🦋",
  "🔥💎👑 bold | rare | powerful | zero apologies ⚡🖤",
  "✈️🌍🎒 travel | explorer • bold | independent • luxury living 🥂💎 👑",
  "✈️🌍🎒 travel | explorer • dreamy | gentle • no limits ⚡👑 🔥",
  "🌊 🌊🐚🌅 ocean | sun | dreamy | gentle | ✨ beach life 🐚🌊",
  "💎 🌊🐚🌅 ocean | sun | moody | luxury | explore more 🗺️✈️ 🖤",
  "🌊 🌸💫🎀 soft | sweet | bold | independent | live in color 🎨🎞️ 💎",
  "✨ 🧁🧸🍭 cute | girlish | dreamy | gentle | 🔥 beach life 🐚🌊",
  "👑 ✈️🌍🎒 travel | explorer | pink | sweet | 💎 good vibes ✨🌸",
  "🌸 🔥💎👑 royal | vip | wandering | free | 🌊 beach life 🐚🌊",
  "📚☕🍂 cozy | classic • pink | sweet • no limits ⚡👑 🔥",
  "🌸 🔥💎👑 royal | vip | pink | sweet | 🖤 good vibes ✨🌸",
  "📚☕🍂 cozy | classic • bold | independent • cozy days 🕯️📚 🌊",
  "🧁🧸🍭 cute | girlish • moody | luxury • beach life 🐚🌊 🌸",
  "🌊 📚☕🍂 cozy | classic | creative | film | 💎 good vibes ✨🌸",
  "🕶️🖤🥂 black | classy • sandy | salty • cozy days 🕯️📚 🖤",
  "☕ 🧁🧸🍭 cute | girlish | moody | luxury | good vibes ✨🌸 👑",
  "✨ 🧁🧸🍭 cute | girlish | sandy | salty | soft girl 🧸🎀 ☕",
  "🖤 🕶️🖤🥂 black | classy | vintage | academic | ☕ live in color 🎨🎞️",
  "✨ 🧁🧸🍭 cute | girlish | bold | independent | no limits ⚡👑 🌸",
  "✨ 📚☕🍂 cozy | classic | dreamy | gentle | beach life 🐚🌊 🌊",
  "🌊 🔥💎👑 royal | vip | dreamy | gentle | explore more 🗺️✈️ 💎",
  "🌸 🧁🧸🍭 cute | girlish | sandy | salty | 🔥 no limits ⚡👑",
  "🌸 🕶️🖤🥂 black | classy | bold | independent | 🖤 luxury living 🥂💎",
  "💎 ✈️🌍🎒 travel | explorer | pink | sweet | 🌸 good vibes ✨🌸",
  "🔥 🔥💎👑 royal | vip | creative | film | no limits ⚡👑 ✨",
  "🔥 🌊🐚🌅 ocean | sun | wandering | free | 👑 beach life 🐚🌊",
  "🌊 ✈️🌍🎒 travel | explorer | bold | independent | soft girl 🧸🎀 ☕",
  "🖤 📚☕🍂 cozy | classic | vintage | academic | 👑 explore more 🗺️✈️",
  "🖤 🕶️🖤🥂 black | classy | pink | sweet | ☕ soft girl 🧸🎀",
  "🔥 ✈️🌍🎒 travel | explorer | pink | sweet | ☕ beach life 🐚🌊",
  "🌊 🎨🎬🍿 artist | movie | pink | sweet | luxury living 🥂💎 ☕",
  "👑 🌸💫🎀 soft | sweet | creative | film | good vibes ✨🌸 💎",
  "🖤 🎨🎬🍿 artist | movie | sandy | salty | 🌸 beach life 🐚🌊",
  "🎨🎬🍿 artist | movie • vintage | academic • no limits ⚡👑 🌸",
  "🖤 📚☕🍂 cozy | classic | vintage | academic | live in color 🎨🎞️ 🔥",
  "☕ 🎨🎬🍿 artist | movie | creative | film | 🔥 no limits ⚡👑",
  "👑 🔥💎👑 royal | vip | pink | sweet | 🌊 luxury living 🥂💎",
  "☕ 🔥💎👑 royal | vip | creative | film | good vibes ✨🌸 ✨",
  "☕ 🧁🧸🍭 cute | girlish | pink | sweet | explore more 🗺️✈️ ✨",
  "🌸💫🎀 soft | sweet • wandering | free • good vibes ✨🌸 💎",
  "👑 📚☕🍂 cozy | classic | pink | sweet | 🌸 beach life 🐚🌊",
  "✈️🌍🎒 travel | explorer • moody | luxury • no limits ⚡👑 🔥",
  "✈️🌍🎒 travel | explorer • vintage | academic • cozy days 🕯️📚 🖤",
  "✨ 🌸💫🎀 soft | sweet | wandering | free | ☕ live in color 🎨🎞️",
  "✈️🌍🎒 travel | explorer • vintage | academic • cozy days 🕯️📚 🌊",
  "✈️🌍🎒 travel | explorer • sandy | salty • beach life 🐚🌊 🔥",
  "✈️🌍🎒 travel | explorer • pink | sweet • no limits ⚡👑 ✨",
  "🧁🧸🍭 cute | girlish • pink | sweet • beach life 🐚🌊 🖤",
  "👑 📚☕🍂 cozy | classic | pink | sweet | luxury living 🥂💎 🌊",
  "👑 🌊🐚🌅 ocean | sun | sandy | salty | soft girl 🧸🎀 ✨",
  "🌸💫🎀 soft | sweet • sandy | salty • cozy days 🕯️📚 💎",
  "🔥💎👑 royal | vip • creative | film • luxury living 🥂💎 🌊",
  "💎 🌊🐚🌅 ocean | sun | sandy | salty | 🌊 beach life 🐚🌊",
  "🌸 📚☕🍂 cozy | classic | dreamy | gentle | explore more 🗺️✈️ 💎",
  "🌸💫🎀 soft | sweet • creative | film • beach life 🐚🌊 💎",
  "💎 🌸💫🎀 soft | sweet | bold | independent | explore more 🗺️✈️ 🖤",
  "🔥 🌸💫🎀 soft | sweet | creative | film | ☕ explore more 🗺️✈️",
  "✨ 🔥💎👑 royal | vip | pink | sweet | luxury living 🥂💎 👑",
  "🕶️🖤🥂 black | classy • dreamy | gentle • good vibes ✨🌸 🔥",
  "🌸 🕶️🖤🥂 black | classy | wandering | free | 🖤 cozy days 🕯️📚",
  "🔥 🧁🧸🍭 cute | girlish | pink | sweet | live in color 🎨🎞️ 💎",
  "💎 🎨🎬🍿 artist | movie | wandering | free | good vibes ✨🌸 🔥",
  "✨ 🧁🧸🍭 cute | girlish | wandering | free | ☕ cozy days 🕯️📚",
  "🌊🐚🌅 ocean | sun • wandering | free • beach life 🐚🌊 👑",
  "🔥 🧁🧸🍭 cute | girlish | moody | luxury | 👑 cozy days 🕯️📚",
  "👑 🌊🐚🌅 ocean | sun | vintage | academic | live in color 🎨🎞️ ☕",
  "📚☕🍂 cozy | classic • pink | sweet • no limits ⚡👑 ✨",
  "📚☕🍂 cozy | classic • dreamy | gentle • soft girl 🧸🎀 ☕",
  "✨ 🎨🎬🍿 artist | movie | vintage | academic | beach life 🐚🌊 👑",
  "🌸💫🎀 soft | sweet • creative | film • beach life 🐚🌊 🔥",
  "🌊 🔥💎👑 royal | vip | moody | luxury | cozy days 🕯️📚 🖤",
  "👑 ✈️🌍🎒 travel | explorer | moody | luxury | luxury living 🥂💎 🔥",
  "💎 🌸💫🎀 soft | sweet | wandering | free | good vibes ✨🌸 ☕",
  "👑 🌊🐚🌅 ocean | sun | sandy | salty | 🌊 no limits ⚡👑",
  "🕶️🖤🥂 black | classy • pink | sweet • luxury living 🥂💎 🔥",
  "☕ 🌸💫🎀 soft | sweet | wandering | free | 🌸 soft girl 🧸🎀",
  "🌸 🔥💎👑 royal | vip | moody | luxury | 🔥 luxury living 🥂💎",
  "✈️🌍🎒 travel | explorer • dreamy | gentle • explore more 🗺️✈️ 🌸",
  "💎 🕶️🖤🥂 black | classy | wandering | free | live in color 🎨🎞️ 🌊",
  "👑 ✈️🌍🎒 travel | explorer | creative | film | 🌊 good vibes ✨🌸",
  "🕶️🖤🥂 black | classy • bold | independent • no limits ⚡👑 👑",
  "👑 🧁🧸🍭 cute | girlish | moody | luxury | 🌊 good vibes ✨🌸",
  "💎 🌊🐚🌅 ocean | sun | moody | luxury | 🖤 no limits ⚡👑",
  "✨ 📚☕🍂 cozy | classic | bold | independent | 🌊 no limits ⚡👑",
  "👑 🧁🧸🍭 cute | girlish | bold | independent | ☕ explore more 🗺️✈️",
  "🖤 ✈️🌍🎒 travel | explorer | dreamy | gentle | cozy days 🕯️📚 👑",
  "📚☕🍂 cozy | classic • vintage | academic • good vibes ✨🌸 ☕",
  "✨ 🕶️🖤🥂 black | classy | creative | film | cozy days 🕯️📚 👑",
  "🌊 🌸💫🎀 soft | sweet | creative | film | 🌸 good vibes ✨🌸",
  "🕶️🖤🥂 black | classy • sandy | salty • beach life 🐚🌊 🌊",
  "💎 🔥💎👑 royal | vip | dreamy | gentle | beach life 🐚🌊 🔥",
  "🖤 📚☕🍂 cozy | classic | vintage | academic | good vibes ✨🌸 🌸",
  "✨ 🌸💫🎀 soft | sweet | creative | film | soft girl 🧸🎀 🌸",
  "✈️🌍🎒 travel | explorer • vintage | academic • cozy days 🕯️📚 💎",
  "🧁🧸🍭 cute | girlish • dreamy | gentle • no limits ⚡👑 💎",
  "✈️🌍🎒 travel | explorer • bold | independent • explore more 🗺️✈️ ✨",
  "🖤 📚☕🍂 cozy | classic | bold | independent | ☕ live in color 🎨🎞️",
  "✨ 🌊🐚🌅 ocean | sun | sandy | salty | 🌊 good vibes ✨🌸",
  "💎 🎨🎬🍿 artist | movie | wandering | free | soft girl 🧸🎀 🖤",
];

export const LOVE_BIOS = [
  "💕 Made of love & stardust | 🌙 Waiting for a love that feels like home",
  "💖 She loves fiercely | 🌸 And even more deeply than she shows",
  "❤️ Stitched with love | star gazer | 🌹 blessed in love 💖",
  "💖 Heart full of romance | sweet talker | happy together 💕 💕",
  "Sweet romance seeker • love letter writer • happy together 💕 ✨",
  "Chasing love stories • warm heart keeper • love is real 💞 💞",
  "🌸 Hopeless romantic | sweet talker | sweet romance ✨ 💖",
  "💖 Chasing love stories | dream sharer | with all my heart 💌 🌹",
  "❤️ Chasing love stories | dream sharer | 💖 blessed in love 💖",
  "Believer in love • star gazer • made for you 🌹 ❤️",
  "🌸 Pure affection | soulmate seeker | sweet romance ✨ 💖",
  "Stitched with love • dream sharer • love first 🌸 💕",
  "🌹 Made of love | dream sharer | with all my heart 💌 ✨",
  "Stitched with love • love letter writer • sweet romance ✨ 🌸",
  "Pure affection • love letter writer • blessed in love 💖 💞",
  "Love is my guide • warm heart keeper • sweet romance ✨ 🌹",
  "Made of love • warm heart keeper • forever yours 💖 ❤️",
  "🌸 Loving fiercely | hug giver | ❤️ happy together 💕",
  "🌹 Loving fiercely | sweet talker | 💕 love first 🌸",
  "❤️ Believer in love | warm heart keeper | ✨ love is real 💞",
  "💌 Loving fiercely | love letter writer | 💖 love is real 💞",
  "❤️ Stitched with love | love letter writer | love first 🌸 💖",
  "Loving fiercely • sweet talker • love is real 💞 💌",
  "Heart full of romance • warm heart keeper • sweet romance ✨ 💌",
  "🌹 Hopeless romantic | sweet talker | made for you 🌹 💌",
  "🌸 Made of love | love letter writer | happy together 💕 💌",
  "💕 Love is my guide | warm heart keeper | 💌 made for you 🌹",
  "Chasing love stories • star gazer • love is real 💞 🌹",
  "Made of love • love letter writer • with all my heart 💌 💖",
  "Pure affection • hug giver • blessed in love 💖 🌸",
  "🌹 Heart full of romance | love letter writer | 💕 blessed in love 💖",
  "Sweet romance seeker • love letter writer • blessed in love 💖 💌",
  "Heart full of romance • warm heart keeper • made for you 🌹 💌",
  "❤️ Believer in love | dream sharer | love first 🌸 💖",
  "Sweet romance seeker • love letter writer • love first 🌸 ❤️",
  "Chasing love stories • hug giver • forever yours 💖 ✨",
  "❤️ Loving fiercely | love letter writer | ✨ sweet romance ✨",
  "Pure affection • warm heart keeper • happy together 💕 🌹",
  "✨ Hopeless romantic | dream sharer | 🌸 happy together 💕",
  "❤️ Heart full of romance | hug giver | 💕 forever yours 💖",
  "💕 Stitched with love | star gazer | love first 🌸 ❤️",
  "Love is my guide • rose collector • forever yours 💖 💕",
  "💞 Sweet romance seeker | soulmate seeker | 🌹 forever yours 💖",
  "Made of love • hug giver • made for you 🌹 ❤️",
  "Stitched with love • star gazer • happy together 💕 💞",
  "🌸 Stitched with love | sweet talker | 💕 with all my heart 💌",
  "Made of love • rose collector • made for you 🌹 💌",
  "Loving fiercely • soulmate seeker • love is real 💞 🌸",
  "✨ Made of love | warm heart keeper | 🌸 with all my heart 💌",
  "✨ Pure affection | rose collector | 💞 with all my heart 💌",
  "Believer in love • star gazer • made for you 🌹 💞",
  "🌹 Pure affection | hug giver | sweet romance ✨ 💖",
  "✨ Made of love | hug giver | blessed in love 💖 🌹",
  "Believer in love • rose collector • blessed in love 💖 ✨",
  "✨ Loving fiercely | rose collector | blessed in love 💖 🌸",
  "❤️ Believer in love | rose collector | 💞 love is real 💞",
  "🌸 Loving fiercely | sweet talker | with all my heart 💌 💖",
  "💕 Stitched with love | star gazer | ❤️ love first 🌸",
  "❤️ Hopeless romantic | hug giver | 💕 sweet romance ✨",
  "❤️ Stitched with love | love letter writer | 💕 happy together 💕",
  "Loving fiercely • sweet talker • love is real 💞 🌸",
  "Sweet romance seeker • star gazer • love first 🌸 ✨",
  "💌 Love is my guide | hug giver | 💖 love is real 💞",
  "Sweet romance seeker • hug giver • love is real 💞 💌",
  "Sweet romance seeker • love letter writer • made for you 🌹 💕",
  "💌 Believer in love | sweet talker | 💖 sweet romance ✨",
  "❤️ Hopeless romantic | hug giver | made for you 🌹 🌸",
  "Love is my guide • warm heart keeper • blessed in love 💖 🌹",
  "Hopeless romantic • hug giver • made for you 🌹 ❤️",
  "💞 Heart full of romance | star gazer | made for you 🌹 🌸",
  "Love is my guide • love letter writer • love is real 💞 🌹",
  "💞 Sweet romance seeker | sweet talker | ✨ blessed in love 💖",
  "🌹 Pure affection | star gazer | sweet romance ✨ ✨",
  "🌸 Love is my guide | star gazer | with all my heart 💌 💖",
  "Loving fiercely • dream sharer • with all my heart 💌 💌",
  "✨ Love is my guide | love letter writer | ❤️ sweet romance ✨",
  "🌹 Heart full of romance | warm heart keeper | 🌸 love first 🌸",
  "💖 Made of love | soulmate seeker | forever yours 💖 ✨",
  "🌸 Loving fiercely | love letter writer | 💞 blessed in love 💖",
  "💖 Love is my guide | sweet talker | happy together 💕 💕",
  "Stitched with love • warm heart keeper • forever yours 💖 💕",
  "Stitched with love • hug giver • forever yours 💖 🌹",
  "💌 Sweet romance seeker | love letter writer | ✨ blessed in love 💖",
  "💕 Chasing love stories | sweet talker | made for you 🌹 💌",
  "Pure affection • rose collector • love first 🌸 💖",
  "❤️ Believer in love | star gazer | 💞 forever yours 💖",
  "💕 Pure affection | hug giver | 🌹 blessed in love 💖",
  "❤️ Pure affection | warm heart keeper | forever yours 💖 💌",
  "💌 Made of love | love letter writer | forever yours 💖 ❤️",
  "Sweet romance seeker • hug giver • love is real 💞 💖",
  "Believer in love • dream sharer • with all my heart 💌 💖",
  "Pure affection • rose collector • forever yours 💖 💞",
  "Sweet romance seeker • love letter writer • love first 🌸 🌸",
  "Made of love • love letter writer • love first 🌸 🌸",
  "💖 Love is my guide | warm heart keeper | ✨ made for you 🌹",
  "Heart full of romance • sweet talker • with all my heart 💌 💕",
  "🌹 Hopeless romantic | star gazer | happy together 💕 💖",
  "✨ Made of love | warm heart keeper | 💕 blessed in love 💖",
  "💖 Love is my guide | star gazer | blessed in love 💖 🌸",
  "💕 Chasing love stories | soulmate seeker | 💞 with all my heart 💌",
];

export const FUNNY_BIOS = [
  "😂 Professional overthinker | 🍕 Pizza before boys | 💤 Sleep is my love language",
  "💤 I function on coffee & denial | 🌮 Tacos & trust issues",
  "🍕 Drama queen in training | overthinker | still sleeping 💤 😜",
  "😏 Functioning on caffeine | overthinker | pizza forever 🍕 😂",
  "😂 Functioning on caffeine | french fry consumer | still sleeping 💤 ☕",
  "😜 Sarcastic beauty | bed sheet tester | 😏 need coffee ☕",
  "Overthinking expert • comedy seeker • need coffee ☕ 🍕",
  "💤 Cute but psycho | snack eater | need coffee ☕ 🙄",
  "😜 Professional napper | bed sheet tester | drama free-ish 🙄 ☕",
  "💤 Cute but psycho | bed sheet tester | drama free-ish 🙄 😏",
  "😜 Overthinking expert | french fry consumer | still sleeping 💤 🍟",
  "😂 Professional napper | overthinker | need coffee ☕ 💤",
  "😏 Overthinking expert | sleeping champion | hustle for food 🍟 💤",
  "🍟 Functioning on caffeine | sleeping champion | just weird 😏 🍕",
  "😏 Overthinking expert | french fry consumer | 😜 still sleeping 💤",
  "😂 Chaos coordinator | snack eater | hustle for food 🍟 🍕",
  "🍕 Pizza over people | pillow lover | 😏 drama free-ish 🙄",
  "🍕 Life is a comedy | sleeping champion | pizza forever 🍕 😜",
  "💤 Sarcastic beauty | overthinker | still sleeping 💤 😂",
  "Adulting check: failed • sleeping champion • not caring 😂 🍟",
  "😜 Overthinking expert | overthinker | 😂 pizza forever 🍕",
  "😏 Functioning on caffeine | bed sheet tester | pizza forever 🍕 😜",
  "🍟 Life is a comedy | overthinker | 🍕 drama free-ish 🙄",
  "🙄 Adulting check: failed | comedy seeker | need coffee ☕ 🍕",
  "🍟 Life is a comedy | couch potato | not caring 😂 🍕",
  "🍟 Sarcastic beauty | overthinker | pizza forever 🍕 💤",
  "🍟 Overthinking expert | overthinker | still sleeping 💤 🙄",
  "Sarcastic beauty • comedy seeker • drama free-ish 🙄 ☕",
  "☕ Functioning on caffeine | french fry consumer | pizza forever 🍕 💤",
  "💤 Sarcastic beauty | overthinker | hustle for food 🍟 🙄",
  "Chaos coordinator • bed sheet tester • still sleeping 💤 🍕",
  "😏 Drama queen in training | overthinker | not caring 😂 ☕",
  "🙄 Cute but psycho | comedy seeker | 🍟 not caring 😂",
  "🍟 Life is a comedy | bed sheet tester | pizza forever 🍕 😂",
  "🍟 Sarcastic beauty | french fry consumer | 😏 hustle for food 🍟",
  "🍕 Pizza over people | overthinker | 😜 just weird 😏",
  "Professional napper • couch potato • not caring 😂 💤",
  "😏 Life is a comedy | pillow lover | pizza forever 🍕 ☕",
  "😏 Sarcastic beauty | french fry consumer | 💤 just weird 😏",
  "😏 Cute but psycho | bed sheet tester | 😂 drama free-ish 🙄",
  "Pizza over people • couch potato • drama free-ish 🙄 😂",
  "🙄 Chaos coordinator | comedy seeker | 😂 need coffee ☕",
  "Adulting check: failed • french fry consumer • need coffee ☕ 🍟",
  "🙄 Overthinking expert | french fry consumer | 💤 drama free-ish 🙄",
  "💤 Drama queen in training | pillow lover | not caring 😂 🙄",
  "Drama queen in training • pillow lover • just weird 😏 🍕",
  "Chaos coordinator • couch potato • send help 😜 😂",
  "😜 Adulting check: failed | overthinker | 😏 just weird 😏",
  "🙄 Drama queen in training | sleeping champion | just weird 😏 😜",
  "Sarcastic beauty • pillow lover • need coffee ☕ 🍟",
  "☕ Pizza over people | pillow lover | 😜 still sleeping 💤",
  "Functioning on caffeine • overthinker • still sleeping 💤 🍕",
  "Cute but psycho • bed sheet tester • just weird 😏 🙄",
  "😜 Professional napper | sleeping champion | not caring 😂 😂",
  "🙄 Drama queen in training | snack eater | 😏 hustle for food 🍟",
  "Drama queen in training • overthinker • just weird 😏 ☕",
  "Functioning on caffeine • sleeping champion • not caring 😂 😏",
  "☕ Professional napper | bed sheet tester | drama free-ish 🙄 😏",
  "💤 Overthinking expert | bed sheet tester | send help 😜 🍕",
  "Professional napper • snack eater • still sleeping 💤 😏",
  "Functioning on caffeine • comedy seeker • pizza forever 🍕 🙄",
  "Sarcastic beauty • bed sheet tester • send help 😜 😜",
  "🙄 Sarcastic beauty | bed sheet tester | just weird 😏 💤",
  "😏 Drama queen in training | snack eater | ☕ send help 😜",
  "😜 Functioning on caffeine | overthinker | drama free-ish 🙄 😏",
  "😂 Functioning on caffeine | pillow lover | 🍟 send help 😜",
  "😜 Life is a comedy | overthinker | drama free-ish 🙄 🙄",
  "☕ Overthinking expert | comedy seeker | not caring 😂 🍕",
  "Pizza over people • overthinker • need coffee ☕ 🍟",
  "🍟 Adulting check: failed | french fry consumer | 💤 drama free-ish 🙄",
  "Cute but psycho • snack eater • hustle for food 🍟 🙄",
  "😏 Adulting check: failed | snack eater | send help 😜 😜",
  "☕ Sarcastic beauty | couch potato | 💤 just weird 😏",
  "😜 Cute but psycho | couch potato | still sleeping 💤 💤",
  "😜 Chaos coordinator | overthinker | drama free-ish 🙄 🍟",
  "🍟 Professional napper | couch potato | 💤 send help 😜",
  "Sarcastic beauty • bed sheet tester • not caring 😂 💤",
  "☕ Drama queen in training | overthinker | 😏 pizza forever 🍕",
  "Sarcastic beauty • comedy seeker • pizza forever 🍕 😂",
  "☕ Chaos coordinator | overthinker | need coffee ☕ 🍟",
  "Sarcastic beauty • comedy seeker • pizza forever 🍕 😜",
  "🍟 Pizza over people | snack eater | ☕ just weird 😏",
  "😂 Sarcastic beauty | pillow lover | drama free-ish 🙄 ☕",
  "🙄 Overthinking expert | french fry consumer | 😏 still sleeping 💤",
  "Functioning on caffeine • snack eater • still sleeping 💤 😂",
  "☕ Cute but psycho | snack eater | 😜 pizza forever 🍕",
  "Life is a comedy • bed sheet tester • need coffee ☕ 💤",
  "😜 Chaos coordinator | sleeping champion | drama free-ish 🙄 🙄",
  "Professional napper • bed sheet tester • send help 😜 🙄",
  "🍕 Adulting check: failed | bed sheet tester | 💤 need coffee ☕",
  "🍟 Life is a comedy | comedy seeker | need coffee ☕ 😏",
  "Pizza over people • bed sheet tester • pizza forever 🍕 😏",
  "🙄 Adulting check: failed | bed sheet tester | 💤 just weird 😏",
  "🍕 Chaos coordinator | french fry consumer | 💤 need coffee ☕",
  "💤 Functioning on caffeine | comedy seeker | send help 😜 🍕",
  "Pizza over people • couch potato • need coffee ☕ 😜",
  "😜 Cute but psycho | french fry consumer | 😂 not caring 😂",
  "😜 Drama queen in training | french fry consumer | just weird 😏 ☕",
  "😜 Pizza over people | sleeping champion | 🍕 pizza forever 🍕",
  "😂 Life is a comedy | bed sheet tester | drama free-ish 🙄 😜",
];

export const HINDI_BIOS = [
  "👑 अपनी मर्जी की मालकिन हूँ मैं | 🌸 किसी के लिए नहीं बदलूँगी | ✨ यही है मेरी पहचान",
  "🔥 जो समझे वो दोस्त, जो न समझे वो अजनबी | 💪 सब मेरे नहीं हो सकते",
  "🔥 सपनों की उड़ान | हंसती मुस्कुराती लड़की | ✨ जीत पक्की है 💪",
  "👑 सीधी सादी लड़की | खुशियाँ बांटने वाली | ✨ घमंड नहीं, स्वाभिमान है 🔥",
  "👑 खुद से प्यार सबसे पहले | सपनों का पीछा करने वाली | खुश रहो हमेशा 🌸 🌸",
  "🔥 मेहनत से बनी पहचान | नेक दिल इंसान | 💖 जीत पक्की है 💪",
  "🌙 दिल साफ़, इरादे नेक | मेहनती लड़की | ✨ जीत पक्की है 💪",
  "खुद से प्यार सबसे पहले • सबकी लाड़ली • घमंड नहीं, स्वाभिमान है 🔥 💪",
  "💪 दिल साफ़, इरादे नेक | मेहनती लड़की | 💕 प्यार ही ज़िन्दगी है 💖",
  "अपनी दुनिया की रानी • खुशियाँ बांटने वाली • जीत पक्की है 💪 💖",
  "💖 सपनों की उड़ान | नेक दिल इंसान | ✨ दिलदार लड़की 💕",
  "तेवर थोड़े तीखे • सपनों का पीछा करने वाली • आसमान छूना है 🌙 ✨",
  "सादगी ही श्रृंगार है • मेहनती लड़की • यही हूँ मैं 👑 💖",
  "पापा की प्रिंसेस • खुशियाँ बांटने वाली • घमंड नहीं, स्वाभिमान है 🔥 🔥",
  "🌸 सीधी सादी लड़की | खुशियाँ बांटने वाली | खुश रहो हमेशा 🌸 💪",
  "सादगी ही श्रृंगार है • स्वाभिमानी नारी • आसमान छूना है 🌙 🌸",
  "पापा की प्रिंसेस • सपनों का पीछा करने वाली • दिलदार लड़की 💕 🌙",
  "सीधी सादी लड़की • सबकी लाड़ली • प्यार ही ज़िन्दगी है 💖 💕",
  "💖 दिल साफ़, इरादे नेक | खुशियाँ बांटने वाली | ✨ दिलदार लड़की 💕",
  "नवाबों की लाड़ली • सच्ची दोस्ती निभाने वाली • घमंड नहीं, स्वाभिमान है 🔥 👑",
  "अपनी दुनिया की रानी • मेहनती लड़की • आसमान छूना है 🌙 💪",
  "सीधी सादी लड़की • खुशियाँ बांटने वाली • घमंड नहीं, स्वाभिमान है 🔥 💖",
  "💪 पापा की प्रिंसेस | नेक दिल इंसान | दिलदार लड़की 💕 👑",
  "तेवर थोड़े तीखे • खुशियाँ बांटने वाली • आसमान छूना है 🌙 💖",
  "👑 पापा की प्रिंसेस | नेक दिल इंसान | 🔥 यही हूँ मैं 👑",
  "सपनों की उड़ान • मेहनती लड़की • प्यार ही ज़िन्दगी है 💖 🌙",
  "💖 तेवर थोड़े तीखे | नेक दिल इंसान | 🔥 घमंड नहीं, स्वाभिमान है 🔥",
  "💖 अपनी दुनिया की रानी | सबकी लाड़ली | 🌙 दिलदार लड़की 💕",
  "सादगी ही श्रृंगार है • सपनों का पीछा करने वाली • जीत पक्की है 💪 👑",
  "सादगी ही श्रृंगार है • सच्ची दोस्ती निभाने वाली • जीत पक्की है 💪 🌙",
  "💪 सादगी ही श्रृंगार है | हंसती मुस्कुराती लड़की | 👑 आसमान छूना है 🌙",
  "💕 खुद से प्यार सबसे पहले | स्वाभिमानी नारी | 🌸 सफलता की ओर ✨",
  "💪 दिल साफ़, इरादे नेक | सपनों का पीछा करने वाली | घमंड नहीं, स्वाभिमान है 🔥 🔥",
  "💖 मेहनत से बनी पहचान | हंसती मुस्कुराती लड़की | 🌙 यही हूँ मैं 👑",
  "👑 मेहनत से बनी पहचान | सबकी लाड़ली | 💖 दिलदार लड़की 💕",
  "🌙 अपनी दुनिया की रानी | हंसती मुस्कुराती लड़की | 💪 आसमान छूना है 🌙",
  "दिल साफ़, इरादे नेक • नेक दिल इंसान • घमंड नहीं, स्वाभिमान है 🔥 ✨",
  "मेहनत से बनी पहचान • हंसती मुस्कुराती लड़की • खुश रहो हमेशा 🌸 💕",
  "खुद से प्यार सबसे पहले • नेक दिल इंसान • घमंड नहीं, स्वाभिमान है 🔥 ✨",
  "✨ अपनी दुनिया की रानी | सपनों का पीछा करने वाली | 🌸 आसमान छूना है 🌙",
  "💕 सीधी सादी लड़की | खुशियाँ बांटने वाली | 🌸 जीत पक्की है 💪",
  "✨ मेहनत से बनी पहचान | नेक दिल इंसान | आसमान छूना है 🌙 💪",
  "सपनों की उड़ान • सपनों का पीछा करने वाली • आसमान छूना है 🌙 💪",
  "🔥 तेवर थोड़े तीखे | सपनों का पीछा करने वाली | 👑 प्यार ही ज़िन्दगी है 💖",
  "मेहनत से बनी पहचान • मेहनती लड़की • प्यार ही ज़िन्दगी है 💖 ✨",
  "मेहनत से बनी पहचान • सबकी लाड़ली • यही हूँ मैं 👑 ✨",
  "नवाबों की लाड़ली • स्वाभिमानी नारी • खुश रहो हमेशा 🌸 💕",
  "सादगी ही श्रृंगार है • खुशियाँ बांटने वाली • सफलता की ओर ✨ 🌙",
  "🌙 नवाबों की लाड़ली | सपनों का पीछा करने वाली | सफलता की ओर ✨ ✨",
  "नवाबों की लाड़ली • स्वाभिमानी नारी • यही हूँ मैं 👑 ✨",
  "👑 पापा की प्रिंसेस | सबकी लाड़ली | आसमान छूना है 🌙 ✨",
  "💕 सपनों की उड़ान | मेहनती लड़की | 🔥 यही हूँ मैं 👑",
  "अपनी दुनिया की रानी • नेक दिल इंसान • यही हूँ मैं 👑 👑",
  "🌙 सीधी सादी लड़की | सपनों का पीछा करने वाली | 💪 घमंड नहीं, स्वाभिमान है 🔥",
  "✨ दिल साफ़, इरादे नेक | सबकी लाड़ली | 🌸 खुश रहो हमेशा 🌸",
  "💖 मेहनत से बनी पहचान | खुशियाँ बांटने वाली | दिलदार लड़की 💕 🌸",
  "💪 सीधी सादी लड़की | खुशियाँ बांटने वाली | 🌙 जीत पक्की है 💪",
  "🔥 खुद से प्यार सबसे पहले | सबकी लाड़ली | सफलता की ओर ✨ 🌸",
  "🌙 खुद से प्यार सबसे पहले | सपनों का पीछा करने वाली | 💕 प्यार ही ज़िन्दगी है 💖",
  "🌸 अपनी दुनिया की रानी | नेक दिल इंसान | 💪 जीत पक्की है 💪",
  "तेवर थोड़े तीखे • नेक दिल इंसान • सफलता की ओर ✨ 💕",
  "पापा की प्रिंसेस • हंसती मुस्कुराती लड़की • दिलदार लड़की 💕 👑",
  "💪 मेहनत से बनी पहचान | सबकी लाड़ली | 🌸 दिलदार लड़की 💕",
  "खुद से प्यार सबसे पहले • नेक दिल इंसान • आसमान छूना है 🌙 👑",
  "💕 सपनों की उड़ान | खुशियाँ बांटने वाली | सफलता की ओर ✨ ✨",
  "👑 पापा की प्रिंसेस | हंसती मुस्कुराती लड़की | आसमान छूना है 🌙 💕",
  "💪 पापा की प्रिंसेस | नेक दिल इंसान | आसमान छूना है 🌙 🌙",
  "💪 नवाबों की लाड़ली | सपनों का पीछा करने वाली | 🌙 घमंड नहीं, स्वाभिमान है 🔥",
  "👑 मेहनत से बनी पहचान | हंसती मुस्कुराती लड़की | 🔥 प्यार ही ज़िन्दगी है 💖",
  "🌙 पापा की प्रिंसेस | मेहनती लड़की | ✨ यही हूँ मैं 👑",
  "🌸 सपनों की उड़ान | हंसती मुस्कुराती लड़की | घमंड नहीं, स्वाभिमान है 🔥 🔥",
  "मेहनत से बनी पहचान • मेहनती लड़की • आसमान छूना है 🌙 💪",
  "💪 नवाबों की लाड़ली | सपनों का पीछा करने वाली | खुश रहो हमेशा 🌸 💕",
  "दिल साफ़, इरादे नेक • सबकी लाड़ली • जीत पक्की है 💪 🔥",
  "👑 सीधी सादी लड़की | स्वाभिमानी नारी | यही हूँ मैं 👑 ✨",
  "पापा की प्रिंसेस • स्वाभिमानी नारी • दिलदार लड़की 💕 🔥",
  "सीधी सादी लड़की • सबकी लाड़ली • दिलदार लड़की 💕 🔥",
  "🌙 नवाबों की लाड़ली | खुशियाँ बांटने वाली | 💖 यही हूँ मैं 👑",
  "पापा की प्रिंसेस • खुशियाँ बांटने वाली • सफलता की ओर ✨ ✨",
  "🌙 पापा की प्रिंसेस | सबकी लाड़ली | ✨ खुश रहो हमेशा 🌸",
  "खुद से प्यार सबसे पहले • सपनों का पीछा करने वाली • सफलता की ओर ✨ 🌙",
  "💕 नवाबों की लाड़ली | सच्ची दोस्ती निभाने वाली | ✨ दिलदार लड़की 💕",
  "💖 पापा की प्रिंसेस | स्वाभिमानी नारी | जीत पक्की है 💪 🌸",
  "🌙 पापा की प्रिंसेस | मेहनती लड़की | ✨ जीत पक्की है 💪",
  "🌸 तेवर थोड़े तीखे | सबकी लाड़ली | दिलदार लड़की 💕 👑",
  "💪 सादगी ही श्रृंगार है | स्वाभिमानी नारी | प्यार ही ज़िन्दगी है 💖 👑",
  "🌙 सपनों की उड़ान | सबकी लाड़ली | दिलदार लड़की 💕 💪",
  "💕 मेहनत से बनी पहचान | सच्ची दोस्ती निभाने वाली | 🔥 खुश रहो हमेशा 🌸",
  "पापा की प्रिंसेस • हंसती मुस्कुराती लड़की • प्यार ही ज़िन्दगी है 💖 🔥",
  "मेहनत से बनी पहचान • सबकी लाड़ली • खुश रहो हमेशा 🌸 💕",
  "अपनी दुनिया की रानी • मेहनती लड़की • प्यार ही ज़िन्दगी है 💖 💕",
  "💪 सपनों की उड़ान | सपनों का पीछा करने वाली | दिलदार लड़की 💕 🌙",
  "💖 सादगी ही श्रृंगार है | नेक दिल इंसान | खुश रहो हमेशा 🌸 👑",
  "नवाबों की लाड़ली • सच्ची दोस्ती निभाने वाली • सफलता की ओर ✨ 🔥",
  "💖 अपनी दुनिया की रानी | नेक दिल इंसान | 🌸 जीत पक्की है 💪",
  "नवाबों की लाड़ली • खुशियाँ बांटने वाली • जीत पक्की है 💪 🌸",
  "✨ नवाबों की लाड़ली | मेहनती लड़की | 👑 दिलदार लड़की 💕",
  "सीधी सादी लड़की • मेहनती लड़की • आसमान छूना है 🌙 🌸",
  "दिल साफ़, इरादे नेक • हंसती मुस्कुराती लड़की • यही हूँ मैं 👑 💕",
  "🔥 सादगी ही श्रृंगार है | खुशियाँ बांटने वाली | जीत पक्की है 💪 👑",
];

export const CLASSY_BIOS = [
  "🥂 Grace under pressure | 💎 Elegance in every step | 🌹 A woman who knows her worth",
  "✨ She is classically trained in the art of being herself | 🥂 No imitation",
  "Sophistication is key • refined taste collector • simply refined ✨ ✨",
  "🌹 Timeless elegance | refined taste collector | pure class 👑 👑",
  "💎 Graceful posture | standard keeper | always elegant 🌹 👠",
  "👑 Timeless beauty | quiet thinker | poised and free ✨ 👠",
  "👠 Timeless elegance | culture explorer | ✨ poised and free ✨",
  "💍 Sophisticated heart | classic fashion seeker | 👠 refined living 🥂",
  "💎 Graceful posture | books and tea lover | ⚜️ pure class 👑",
  "Refined choices • refined taste collector • simply refined ✨ 👠",
  "👠 Pure refinement | elegance promoter | ⚜️ stay classy 🥂",
  "💎 Sophisticated heart | elegance promoter | 🥂 elegant soul 🌹",
  "🌹 Poised and polished | refined taste collector | 💍 timeless grace 💎",
  "💍 Lady of class | classic fashion seeker | refined living 🥂 👠",
  "🌹 Sophistication is key | quiet thinker | poised and free ✨ ✨",
  "🥂 Lady of class | elegance promoter | refined living 🥂 💎",
  "Lady of class • classic fashion seeker • elegant soul 🌹 👠",
  "✨ Pure refinement | quiet thinker | 💎 pure class 👑",
  "🌹 Timeless elegance | classic fashion seeker | simply refined ✨ 👠",
  "⚜️ Class is permanent | elegance promoter | 💍 refined living 🥂",
  "🌹 Sophistication is key | quiet thinker | pure class 👑 👑",
  "👠 Class is permanent | quiet thinker | stay classy 🥂 🥂",
  "Timeless beauty • classic fashion seeker • always elegant 🌹 🌹",
  "Timeless beauty • refined taste collector • refined living 🥂 ⚜️",
  "🥂 Class is permanent | books and tea lover | poised and free ✨ 👑",
  "👑 Timeless elegance | culture explorer | 💍 always elegant 🌹",
  "Sophisticated heart • culture explorer • elegant soul 🌹 👑",
  "👠 Sophistication is key | books and tea lover | simply refined ✨ 🥂",
  "Sophisticated heart • books and tea lover • simply refined ✨ 💍",
  "✨ Pure refinement | culture explorer | timeless grace 💎 👠",
  "👠 Poised and polished | art lover | 💍 stay classy 🥂",
  "Pure refinement • quiet thinker • always elegant 🌹 💍",
  "🥂 Lady of class | refined taste collector | 👠 timeless grace 💎",
  "👠 Poised and polished | classic fashion seeker | refined living 🥂 💍",
  "👠 Sophistication is key | standard keeper | simply refined ✨ 🥂",
  "⚜️ Graceful posture | culture explorer | simply refined ✨ 💍",
  "Lady of class • culture explorer • pure class 👑 💍",
  "💍 Timeless beauty | elegance promoter | 🌹 pure class 👑",
  "💍 Refined choices | quiet thinker | stay classy 🥂 🌹",
  "Refined choices • books and tea lover • simply refined ✨ 💎",
  "Graceful posture • culture explorer • timeless grace 💎 🥂",
  "Poised and polished • books and tea lover • poised and free ✨ 🥂",
  "Timeless beauty • classic fashion seeker • timeless grace 💎 💎",
  "🥂 Graceful posture | standard keeper | pure class 👑 ✨",
  "💍 Lady of class | classic fashion seeker | always elegant 🌹 💎",
  "💎 Pure refinement | classic fashion seeker | 🌹 always elegant 🌹",
  "🌹 Class is permanent | culture explorer | ✨ pure class 👑",
  "Sophistication is key • refined taste collector • stay classy 🥂 🌹",
  "💍 Sophisticated heart | classic fashion seeker | timeless grace 💎 👠",
  "✨ Refined choices | refined taste collector | pure class 👑 🌹",
  "⚜️ Graceful posture | standard keeper | elegant soul 🌹 👑",
  "Lady of class • elegance promoter • timeless grace 💎 🌹",
  "🥂 Timeless beauty | refined taste collector | pure class 👑 💍",
  "⚜️ Timeless elegance | classic fashion seeker | stay classy 🥂 👠",
  "🥂 Timeless beauty | art lover | 🌹 elegant soul 🌹",
  "👠 Timeless elegance | quiet thinker | ✨ elegant soul 🌹",
  "✨ Poised and polished | standard keeper | 🌹 always elegant 🌹",
  "💍 Timeless beauty | refined taste collector | ⚜️ timeless grace 💎",
  "💎 Timeless beauty | culture explorer | 🥂 refined living 🥂",
  "✨ Poised and polished | elegance promoter | poised and free ✨ 👑",
  "🌹 Lady of class | quiet thinker | pure class 👑 🥂",
  "✨ Lady of class | quiet thinker | 👠 timeless grace 💎",
  "✨ Class is permanent | art lover | pure class 👑 ⚜️",
  "Timeless elegance • classic fashion seeker • simply refined ✨ ✨",
  "Poised and polished • culture explorer • timeless grace 💎 ⚜️",
  "Pure refinement • books and tea lover • elegant soul 🌹 👑",
  "💍 Lady of class | culture explorer | pure class 👑 💎",
  "Timeless beauty • elegance promoter • stay classy 🥂 💎",
  "Sophisticated heart • refined taste collector • timeless grace 💎 💍",
  "✨ Lady of class | elegance promoter | 💍 elegant soul 🌹",
  "👠 Timeless beauty | refined taste collector | simply refined ✨ 🌹",
  "💍 Lady of class | books and tea lover | 🌹 simply refined ✨",
  "💍 Lady of class | classic fashion seeker | 🥂 timeless grace 💎",
  "👠 Sophisticated heart | standard keeper | stay classy 🥂 💎",
  "Poised and polished • quiet thinker • always elegant 🌹 🌹",
  "✨ Graceful posture | standard keeper | refined living 🥂 💍",
  "Sophisticated heart • books and tea lover • elegant soul 🌹 🥂",
  "🥂 Refined choices | books and tea lover | 💎 simply refined ✨",
  "👠 Poised and polished | classic fashion seeker | 💍 always elegant 🌹",
  "👠 Graceful posture | refined taste collector | 💍 pure class 👑",
  "💍 Pure refinement | books and tea lover | 🌹 poised and free ✨",
  "Poised and polished • classic fashion seeker • elegant soul 🌹 👠",
  "✨ Poised and polished | art lover | simply refined ✨ 💎",
  "💎 Timeless elegance | quiet thinker | 👑 stay classy 🥂",
  "💍 Lady of class | art lover | timeless grace 💎 🥂",
  "✨ Lady of class | books and tea lover | always elegant 🌹 👑",
  "⚜️ Pure refinement | refined taste collector | 👠 stay classy 🥂",
  "⚜️ Timeless elegance | refined taste collector | always elegant 🌹 👠",
  "👠 Timeless beauty | art lover | pure class 👑 ✨",
  "✨ Class is permanent | classic fashion seeker | poised and free ✨ 🌹",
  "✨ Graceful posture | classic fashion seeker | 👠 poised and free ✨",
  "🌹 Sophisticated heart | art lover | 🥂 pure class 👑",
  "💎 Timeless elegance | quiet thinker | elegant soul 🌹 ⚜️",
  "👠 Timeless beauty | standard keeper | refined living 🥂 💎",
  "💍 Refined choices | culture explorer | timeless grace 💎 👠",
  "💍 Graceful posture | art lover | pure class 👑 👠",
  "Sophistication is key • art lover • elegant soul 🌹 👑",
  "🌹 Lady of class | classic fashion seeker | ✨ timeless grace 💎",
  "Timeless beauty • refined taste collector • stay classy 🥂 👑",
  "👠 Lady of class | books and tea lover | timeless grace 💎 💍",
];

export const TRENDING_BIOS = [
  "✨ In my main character era | 🌙 Unbothered. Glowing. Levelling up daily",
  "🌸 Soft girl era, activated | 💕 Healing, growing, and choosing peace",
  "👑 In my glow era | habit tracker | winning silently 📈 ✨",
  "📈 2026 upgrade | peace seeker | ⚡ winning silently 📈",
  "Abundance mindset • peace seeker • glow permanent ✨ 👑",
  "Main character energy • high frequency radiator • abundant life 🌸 👑",
  "Abundance mindset • positive thinker • peace first 💕 🌿",
  "💫 Abundance mindset | positive thinker | 💎 peace first 💕",
  "✨ Chasing new horizons | daily meditator | main character 👑 💎",
  "💎 In my glow era | travel explorer | 📈 unstoppable V2 ⚡",
  "Main character energy • asset builder • glow permanent ✨ 💎",
  "👑 Self-love journey | positive thinker | unstoppable V2 ⚡ ✨",
  "💎 2026 upgrade | positive thinker | healing era 💫 ✨",
  "💫 In my glow era | peace seeker | 🌸 peace first 💕",
  "💎 CEO of my path | wellness chaser | healing era 💫 ⚡",
  "✨ CEO of my path | habit tracker | 💫 healing era 💫",
  "💎 Self-love journey | asset builder | 👑 winning silently 📈",
  "👑 Abundance mindset | travel explorer | abundant life 🌸 🌸",
  "💫 CEO of my path | wellness chaser | ✨ winning silently 📈",
  "✨ Levelled up female | peace seeker | 📈 thriving daily 🌿",
  "📈 In my glow era | positive thinker | unstoppable V2 ⚡ 🌿",
  "⚡ Levelled up female | habit tracker | ✨ thriving daily 🌿",
  "Abundance mindset • daily meditator • winning silently 📈 📈",
  "⚡ In my glow era | high frequency radiator | 🌸 healing era 💫",
  "🌸 In my glow era | wellness chaser | unstoppable V2 ⚡ 💫",
  "Healing and thriving • positive thinker • winning silently 📈 🌸",
  "🌿 Self-love journey | daily meditator | peace first 💕 💫",
  "✨ 2026 upgrade | wellness chaser | ⚡ peace first 💕",
  "🌸 Abundance mindset | asset builder | 💎 thriving daily 🌿",
  "Main character energy • asset builder • glow permanent ✨ ✨",
  "Main character energy • travel explorer • glow permanent ✨ 💎",
  "🌸 Protecting my peace | high frequency radiator | ✨ abundant life 🌸",
  "📈 In my glow era | peace seeker | 🌸 unstoppable V2 ⚡",
  "Self-love journey • wellness chaser • glow permanent ✨ 💎",
  "✨ Self-love journey | asset builder | 💎 peace first 💕",
  "🌸 Chasing new horizons | wellness chaser | ✨ abundant life 🌸",
  "Main character energy • wellness chaser • main character 👑 🌿",
  "💫 2026 upgrade | habit tracker | main character 👑 👑",
  "In my glow era • travel explorer • winning silently 📈 📈",
  "💎 Protecting my peace | travel explorer | 🌿 main character 👑",
  "✨ Chasing new horizons | peace seeker | peace first 💕 👑",
  "⚡ Abundance mindset | daily meditator | unstoppable V2 ⚡ 💫",
  "💫 Abundance mindset | asset builder | 💎 peace first 💕",
  "2026 upgrade • positive thinker • peace first 💕 🌿",
  "✨ Healing and thriving | asset builder | thriving daily 🌿 💎",
  "💎 In my glow era | wellness chaser | healing era 💫 💫",
  "💫 2026 upgrade | positive thinker | unstoppable V2 ⚡ 📈",
  "🌸 In my glow era | positive thinker | glow permanent ✨ ⚡",
  "🌿 Levelled up female | asset builder | main character 👑 💎",
  "✨ Protecting my peace | positive thinker | glow permanent ✨ 💫",
  "CEO of my path • travel explorer • healing era 💫 🌿",
  "💫 Levelled up female | wellness chaser | main character 👑 ✨",
  "👑 CEO of my path | asset builder | 📈 glow permanent ✨",
  "🌿 Main character energy | positive thinker | healing era 💫 💎",
  "📈 Chasing new horizons | positive thinker | main character 👑 🌸",
  "💫 Healing and thriving | travel explorer | 📈 healing era 💫",
  "💫 Chasing new horizons | positive thinker | ✨ unstoppable V2 ⚡",
  "👑 Protecting my peace | wellness chaser | winning silently 📈 ⚡",
  "💎 In my glow era | peace seeker | 💫 main character 👑",
  "👑 Main character energy | habit tracker | 📈 abundant life 🌸",
  "Levelled up female • positive thinker • thriving daily 🌿 💎",
  "💎 Chasing new horizons | habit tracker | 🌿 thriving daily 🌿",
  "💫 Self-love journey | daily meditator | healing era 💫 💎",
  "Self-love journey • wellness chaser • winning silently 📈 📈",
  "CEO of my path • asset builder • main character 👑 🌸",
  "✨ Levelled up female | positive thinker | 💎 healing era 💫",
  "Protecting my peace • positive thinker • unstoppable V2 ⚡ 💎",
  "🌿 Chasing new horizons | habit tracker | peace first 💕 📈",
  "Healing and thriving • habit tracker • healing era 💫 🌿",
  "🌿 Main character energy | peace seeker | abundant life 🌸 💫",
  "Main character energy • asset builder • peace first 💕 ✨",
  "🌿 Abundance mindset | positive thinker | 💫 winning silently 📈",
  "Protecting my peace • travel explorer • winning silently 📈 ✨",
  "✨ Chasing new horizons | high frequency radiator | 💎 unstoppable V2 ⚡",
  "💫 Levelled up female | travel explorer | unstoppable V2 ⚡ 💎",
  "Levelled up female • habit tracker • thriving daily 🌿 ⚡",
  "Abundance mindset • high frequency radiator • unstoppable V2 ⚡ 💫",
  "👑 Levelled up female | daily meditator | 🌿 peace first 💕",
  "In my glow era • habit tracker • peace first 💕 ⚡",
  "⚡ Self-love journey | high frequency radiator | ✨ winning silently 📈",
  "In my glow era • travel explorer • main character 👑 ⚡",
  "Abundance mindset • high frequency radiator • abundant life 🌸 📈",
  "🌿 Main character energy | positive thinker | thriving daily 🌿 🌸",
  "💎 Main character energy | travel explorer | glow permanent ✨ ✨",
  "🌿 Abundance mindset | asset builder | unstoppable V2 ⚡ 💫",
  "✨ CEO of my path | asset builder | ⚡ thriving daily 🌿",
  "📈 In my glow era | travel explorer | peace first 💕 👑",
  "🌸 Healing and thriving | high frequency radiator | thriving daily 🌿 📈",
  "📈 Healing and thriving | wellness chaser | winning silently 📈 💎",
  "💎 Protecting my peace | peace seeker | healing era 💫 🌿",
  "🌸 In my glow era | travel explorer | 📈 thriving daily 🌿",
  "💎 Abundance mindset | positive thinker | ✨ thriving daily 🌿",
  "Main character energy • peace seeker • thriving daily 🌿 ⚡",
  "💫 Protecting my peace | travel explorer | 👑 unstoppable V2 ⚡",
  "Self-love journey • habit tracker • unstoppable V2 ⚡ 👑",
  "🌿 In my glow era | wellness chaser | 🌸 main character 👑",
  "🌸 Abundance mindset | habit tracker | unstoppable V2 ⚡ ⚡",
  "Main character energy • positive thinker • unstoppable V2 ⚡ 💎",
  "✨ Abundance mindset | daily meditator | 🌸 thriving daily 🌿",
  "2026 upgrade • high frequency radiator • peace first 💕 📈",
];

export const COOL_BIOS = [
  "👟 Sneaker queen | 🤘 Wild heart, free mind | ⚡ I don't follow trends, I set them",
  "🎸 Rockstar vibe in a pop world | 🖤 Dressed in denim",
  "Riding my own wave • streetwear shopper • unbothered 🖤 🤘",
  "🤘 Skating through life | bass listener | 🕶️ cool energy ⚡",
  "🖤 Skating through life | backstage traveler | cool energy ⚡ ⚡",
  "🖤 Riding my own wave | playlist creator | 🤘 riding high ⚡",
  "👟 Living on my rules | backstage traveler | rock on 🤘 🖤",
  "🕶️ Skating through life | midnight talker | 👟 riding high ⚡",
  "Cool girl aesthetic • skateboarder girl • cool energy ⚡ 👟",
  "👟 Too cool to care | bass listener | cool kid vibes 👟 🛹",
  "🕶️ Sneaker lover always | midnight talker | stay wild 🕶️ 🤘",
  "✌️ Living on my rules | streetwear shopper | 🕶️ cool kid vibes 👟",
  "Wild spirit free mind • skateboarder girl • rock on 🤘 ⚡",
  "✌️ Cool girl aesthetic | playlist creator | 🕶️ live free ✌️",
  "🤘 Sneaker lover always | adrenaline seeker | street style 👟 🕶️",
  "Wild spirit free mind • midnight talker • live free ✌️ ⚡",
  "🕶️ Rockstar vibes daily | streetwear shopper | street style 👟 🎸",
  "👟 Wild spirit free mind | retro gamer | live free ✌️ 🤘",
  "Living on my rules • retro gamer • cool energy ⚡ 🤘",
  "⚡ Wild spirit free mind | midnight talker | street style 👟 ✌️",
  "✌️ Rockstar vibes daily | bass listener | 👟 rock on 🤘",
  "🕶️ Denim jacket girl | bass listener | street style 👟 👟",
  "🕶️ Riding my own wave | playlist creator | unbothered 🖤 🛹",
  "Denim jacket girl • playlist creator • cool kid vibes 👟 ⚡",
  "🛹 Too cool to care | skateboarder girl | 🕶️ riding high ⚡",
  "Riding my own wave • skateboarder girl • cool energy ⚡ ✌️",
  "🖤 Rockstar vibes daily | streetwear shopper | street style 👟 👟",
  "🕶️ Rockstar vibes daily | midnight talker | 👟 stay wild 🕶️",
  "Sneaker lover always • skateboarder girl • street style 👟 ✌️",
  "🤘 Riding my own wave | playlist creator | cool energy ⚡ 🕶️",
  "🤘 Setting the trends | skateboarder girl | ⚡ riding high ⚡",
  "🤘 Cool girl aesthetic | skateboarder girl | 🛹 stay wild 🕶️",
  "🕶️ Skating through life | retro gamer | riding high ⚡ 🛹",
  "🖤 Denim jacket girl | skateboarder girl | 🎸 unbothered 🖤",
  "Sneaker lover always • retro gamer • cool energy ⚡ 🤘",
  "🎸 Living on my rules | backstage traveler | 🛹 cool energy ⚡",
  "Denim jacket girl • adrenaline seeker • riding high ⚡ 🎸",
  "Living on my rules • playlist creator • unbothered 🖤 ⚡",
  "🖤 Skating through life | retro gamer | 🛹 cool energy ⚡",
  "✌️ Denim jacket girl | bass listener | ⚡ rock on 🤘",
  "🕶️ Skating through life | skateboarder girl | riding high ⚡ 👟",
  "Cool girl aesthetic • midnight talker • cool energy ⚡ 🛹",
  "🛹 Skating through life | retro gamer | rock on 🤘 👟",
  "🛹 Living on my rules | backstage traveler | 🖤 stay wild 🕶️",
  "Rockstar vibes daily • bass listener • live free ✌️ 👟",
  "👟 Sneaker lover always | skateboarder girl | ✌️ cool energy ⚡",
  "Riding my own wave • backstage traveler • unbothered 🖤 🎸",
  "Sneaker lover always • backstage traveler • cool kid vibes 👟 🤘",
  "Denim jacket girl • playlist creator • stay wild 🕶️ 🛹",
  "🖤 Too cool to care | retro gamer | 🛹 street style 👟",
  "⚡ Wild spirit free mind | playlist creator | 🖤 live free ✌️",
  "Sneaker lover always • adrenaline seeker • unbothered 🖤 👟",
  "🛹 Riding my own wave | playlist creator | 🖤 rock on 🤘",
  "✌️ Living on my rules | backstage traveler | ⚡ riding high ⚡",
  "Setting the trends • skateboarder girl • cool energy ⚡ ⚡",
  "🕶️ Denim jacket girl | skateboarder girl | 👟 riding high ⚡",
  "🛹 Setting the trends | skateboarder girl | 🎸 unbothered 🖤",
  "🤘 Denim jacket girl | playlist creator | riding high ⚡ 🖤",
  "🤘 Living on my rules | playlist creator | unbothered 🖤 ✌️",
  "🎸 Denim jacket girl | skateboarder girl | cool energy ⚡ 🤘",
  "👟 Riding my own wave | retro gamer | cool kid vibes 👟 🤘",
  "Cool girl aesthetic • streetwear shopper • street style 👟 🖤",
  "Rockstar vibes daily • adrenaline seeker • live free ✌️ ✌️",
  "✌️ Living on my rules | adrenaline seeker | cool kid vibes 👟 🤘",
  "👟 Skating through life | adrenaline seeker | 🤘 riding high ⚡",
  "🎸 Too cool to care | skateboarder girl | 🛹 live free ✌️",
  "👟 Sneaker lover always | streetwear shopper | live free ✌️ ✌️",
  "🎸 Rockstar vibes daily | bass listener | 🛹 stay wild 🕶️",
  "🛹 Denim jacket girl | playlist creator | 🎸 live free ✌️",
  "🕶️ Wild spirit free mind | adrenaline seeker | ⚡ unbothered 🖤",
  "Denim jacket girl • streetwear shopper • riding high ⚡ 🎸",
  "Cool girl aesthetic • bass listener • riding high ⚡ 🎸",
  "🕶️ Cool girl aesthetic | skateboarder girl | ⚡ stay wild 🕶️",
  "Wild spirit free mind • playlist creator • street style 👟 👟",
  "🖤 Living on my rules | retro gamer | 🎸 stay wild 🕶️",
  "🤘 Wild spirit free mind | backstage traveler | cool energy ⚡ ✌️",
  "🛹 Denim jacket girl | playlist creator | live free ✌️ 🕶️",
  "🤘 Too cool to care | playlist creator | ✌️ unbothered 🖤",
  "Denim jacket girl • skateboarder girl • rock on 🤘 ✌️",
  "Living on my rules • streetwear shopper • unbothered 🖤 👟",
  "⚡ Living on my rules | midnight talker | live free ✌️ 🕶️",
  "Living on my rules • streetwear shopper • cool energy ⚡ ✌️",
  "⚡ Sneaker lover always | bass listener | cool energy ⚡ 🖤",
  "🤘 Riding my own wave | midnight talker | 🖤 unbothered 🖤",
  "🎸 Denim jacket girl | bass listener | 🖤 stay wild 🕶️",
  "⚡ Living on my rules | streetwear shopper | 🕶️ live free ✌️",
  "Sneaker lover always • streetwear shopper • riding high ⚡ 🎸",
  "✌️ Setting the trends | streetwear shopper | 🛹 street style 👟",
  "🛹 Skating through life | midnight talker | 🤘 street style 👟",
  "🛹 Too cool to care | retro gamer | stay wild 🕶️ 🤘",
  "🎸 Rockstar vibes daily | streetwear shopper | ⚡ unbothered 🖤",
  "🖤 Setting the trends | bass listener | cool energy ⚡ ⚡",
  "✌️ Sneaker lover always | skateboarder girl | 🤘 cool kid vibes 👟",
  "⚡ Setting the trends | adrenaline seeker | street style 👟 👟",
  "👟 Rockstar vibes daily | bass listener | 🤘 riding high ⚡",
  "🛹 Rockstar vibes daily | adrenaline seeker | riding high ⚡ 🕶️",
  "🎸 Wild spirit free mind | skateboarder girl | 🖤 street style 👟",
  "🤘 Denim jacket girl | backstage traveler | 🎸 street style 👟",
  "✌️ Living on my rules | retro gamer | cool energy ⚡ 👟",
  "🎸 Wild spirit free mind | playlist creator | rock on 🤘 🕶️",
];

